## use only app, db, redis and traeffic as proxy
## think of creating docker-stack-staging.yml -- with also mailhog and redis webui
version: '3.9'

services:
    ### Reverse-Proxy (traefik) ###
#    proxy:
#        image: traefik:2.5.3
#        ports:
#            # The HTTP port
#            - 80:80
#        volumes:
#            # So that Traefik can listen to the Docker events
#            - /var/run/docker.sock:/var/run/docker.sock

    ### APP (php-fpm) ###
    app:
        image: ${IMAGE_APP:-vasymus/mpl}:${IMAGE_APP_TAG:-latest}
        environment:
            - APP_NAME=${APP_NAME}
            - APP_KEY=${APP_KEY}
            - APP_URL=${APP_URL}
            - DB_HOST=${DB_HOST:-db}
            - DB_DATABASE=${MYSQL_DATABASE:-mpl}
            - DB_USERNAME=${MYSQL_USER}
            - DB_PASSWORD=${MYSQL_PASSWORD}
            - CACHE_DRIVER=${CACHE_DRIVER:-database}
            - FILESYSTEM_DRIVER=local
            - QUEUE_CONNECTION=${QUEUE_CONNECTION:-database}
            - SESSION_DRIVER=${SESSION_DRIVER:-database}
            - REDIS_HOST=redis
            - MAIL_MAILER=mailgun
            - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
            - MAILGUN_SECRET=${MAILGUN_SECRET}
            - MAILGUN_ENDPOINT=api.mailgun.net
            - MAIL_FROM_ADDRESS=null
            - MAIL_FROM_NAME=${MAIL_FROM_NAME:-Parket}
        ports:
            - 80:80
#        labels:
#            - traefik.http.routers.app.rule=Host(`104.248.206.54`)
#            - traefik.http.services.app.loadbalancer.server.port=80
            #- traefik.http.routers.blog.tls=true
            #- traefik.http.routers.blog.tls.certresolver=lets-encrypt
            #- traefik.port=80

    ### DB (MariaDB) ###
    db:
        image: mariadb:10.6.4
        volumes:
            - mariadb-db-data:/var/lib/mysql
        deploy:
            placement:
                constraints: [node.role == manager]
        environment:
            # MYSQL_ROOT_PASSWORD is the only required
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE:-mpl}
            # didn't want to add any bind mount or additional Dockerfile, so put it to env variable
            # $$ is used for escaping from docker-compose @see https://docs.docker.com/compose/environment-variables/#substitute-environment-variables-in-compose-files
            # Init script will be run ONLY on first initialization
            - |
                MYSQL_CONFIG=
                [mysqld]
                # MariaDB database server configuration file.
                #
                # You can use this file to overwrite the default configuration
                #
                # For explanations see
                # https://mariadb.com/kb/en/configuring-mariadb-with-option-files/
                default_time_zone='UTC'
        # didn't want to add any bind mount or additional Dockerfile
        command:
            bash -c 'echo "$$MYSQL_CONFIG" > /etc/mysql/conf.d/my.cnf
            && chmod 555 /etc/mysql/conf.d/my.cnf
            && docker-entrypoint.sh mysqld'
#        healthcheck:
#            test: [ "CMD", "mysqladmin -u root -p$$(cat $$MYSQL_ROOT_PASSWORD) ping -h localhost" ]
#            interval: 10s
#            timeout: 20s
#            retries: 10

    ### Redis ###
    #redis:
    #    image: redis:6.2.6
    #    volumes:
    #        - redis-data:/data

volumes:
    mariadb-db-data:
    #redis-data:
