<?php

return array(
    0 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18452,
            '~ID' => '18452',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '341',
            '~XML_ID' => '341',
            'NAME' => '1',
            '~NAME' => '1',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '1',
            '~SORT' => '1',
            'PREVIEW_TEXT' => 'отшлифованная поверхность
',
            '~PREVIEW_TEXT' => 'отшлифованная поверхность
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1386',
            '~IBLOCK_SECTION_ID' => '1386',
            'DETAIL_PAGE_URL' => '/photos/evrotsiklevka-parketa/',
            '~DETAIL_PAGE_URL' => '/photos/evrotsiklevka-parketa/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 35924,
                    'SRC' => '/upload/iblock/8b9/8b9b5c6923d5669c950f045aab4faf27.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '35924',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '341',
            '~EXTERNAL_ID' => '341',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/evrotsiklevka-parketa/index.php?action=BUY&id=18452',
            'BUY_URL' => '/photos/evrotsiklevka-parketa/index.php?action=BUY&amp;id=18452',
            '~ADD_URL' => '/photos/evrotsiklevka-parketa/index.php?action=ADD2BASKET&id=18452',
            'ADD_URL' => '/photos/evrotsiklevka-parketa/index.php?action=ADD2BASKET&amp;id=18452',
            '~SUBSCRIBE_URL' => '/photos/evrotsiklevka-parketa/index.php?action=SUBSCRIBE_PRODUCT&id=18452',
            'SUBSCRIBE_URL' => '/photos/evrotsiklevka-parketa/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18452',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 35924,
                    'SRC' => '/upload/iblock/8b9/8b9b5c6923d5669c950f045aab4faf27.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 35924,
                    'SRC' => '/upload/iblock/8b9/8b9b5c6923d5669c950f045aab4faf27.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 35924,
                    'SRC' => '/upload/iblock/8b9/8b9b5c6923d5669c950f045aab4faf27.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    1 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18453,
            '~ID' => '18453',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '342',
            '~XML_ID' => '342',
            'NAME' => '2',
            '~NAME' => '2',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '2',
            '~SORT' => '2',
            'PREVIEW_TEXT' => '',
            '~PREVIEW_TEXT' => '',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1386',
            '~IBLOCK_SECTION_ID' => '1386',
            'DETAIL_PAGE_URL' => '/photos/evrotsiklevka-parketa/',
            '~DETAIL_PAGE_URL' => '/photos/evrotsiklevka-parketa/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 35925,
                    'SRC' => '/upload/iblock/f58/f581e908c3d987bbd0e2f4743c29da4d.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '35925',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '342',
            '~EXTERNAL_ID' => '342',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/evrotsiklevka-parketa/index.php?action=BUY&id=18453',
            'BUY_URL' => '/photos/evrotsiklevka-parketa/index.php?action=BUY&amp;id=18453',
            '~ADD_URL' => '/photos/evrotsiklevka-parketa/index.php?action=ADD2BASKET&id=18453',
            'ADD_URL' => '/photos/evrotsiklevka-parketa/index.php?action=ADD2BASKET&amp;id=18453',
            '~SUBSCRIBE_URL' => '/photos/evrotsiklevka-parketa/index.php?action=SUBSCRIBE_PRODUCT&id=18453',
            'SUBSCRIBE_URL' => '/photos/evrotsiklevka-parketa/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18453',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 35925,
                    'SRC' => '/upload/iblock/f58/f581e908c3d987bbd0e2f4743c29da4d.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 35925,
                    'SRC' => '/upload/iblock/f58/f581e908c3d987bbd0e2f4743c29da4d.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 35925,
                    'SRC' => '/upload/iblock/f58/f581e908c3d987bbd0e2f4743c29da4d.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    2 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18454,
            '~ID' => '18454',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '343',
            '~XML_ID' => '343',
            'NAME' => '3',
            '~NAME' => '3',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '3',
            '~SORT' => '3',
            'PREVIEW_TEXT' => 'поверхность идеально зашлифована
',
            '~PREVIEW_TEXT' => 'поверхность идеально зашлифована
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1386',
            '~IBLOCK_SECTION_ID' => '1386',
            'DETAIL_PAGE_URL' => '/photos/evrotsiklevka-parketa/',
            '~DETAIL_PAGE_URL' => '/photos/evrotsiklevka-parketa/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 35926,
                    'SRC' => '/upload/iblock/4c7/4c73ae69ef08bedc704cf974c259c6c2.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '35926',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '343',
            '~EXTERNAL_ID' => '343',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/evrotsiklevka-parketa/index.php?action=BUY&id=18454',
            'BUY_URL' => '/photos/evrotsiklevka-parketa/index.php?action=BUY&amp;id=18454',
            '~ADD_URL' => '/photos/evrotsiklevka-parketa/index.php?action=ADD2BASKET&id=18454',
            'ADD_URL' => '/photos/evrotsiklevka-parketa/index.php?action=ADD2BASKET&amp;id=18454',
            '~SUBSCRIBE_URL' => '/photos/evrotsiklevka-parketa/index.php?action=SUBSCRIBE_PRODUCT&id=18454',
            'SUBSCRIBE_URL' => '/photos/evrotsiklevka-parketa/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18454',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 35926,
                    'SRC' => '/upload/iblock/4c7/4c73ae69ef08bedc704cf974c259c6c2.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 35926,
                    'SRC' => '/upload/iblock/4c7/4c73ae69ef08bedc704cf974c259c6c2.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 35926,
                    'SRC' => '/upload/iblock/4c7/4c73ae69ef08bedc704cf974c259c6c2.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    3 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18455,
            '~ID' => '18455',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '344',
            '~XML_ID' => '344',
            'NAME' => '4',
            '~NAME' => '4',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '4',
            '~SORT' => '4',
            'PREVIEW_TEXT' => '',
            '~PREVIEW_TEXT' => '',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1386',
            '~IBLOCK_SECTION_ID' => '1386',
            'DETAIL_PAGE_URL' => '/photos/evrotsiklevka-parketa/',
            '~DETAIL_PAGE_URL' => '/photos/evrotsiklevka-parketa/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 35927,
                    'SRC' => '/upload/iblock/896/896b72ca05ed251d8ec1507884b98cd1.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '35927',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '344',
            '~EXTERNAL_ID' => '344',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/evrotsiklevka-parketa/index.php?action=BUY&id=18455',
            'BUY_URL' => '/photos/evrotsiklevka-parketa/index.php?action=BUY&amp;id=18455',
            '~ADD_URL' => '/photos/evrotsiklevka-parketa/index.php?action=ADD2BASKET&id=18455',
            'ADD_URL' => '/photos/evrotsiklevka-parketa/index.php?action=ADD2BASKET&amp;id=18455',
            '~SUBSCRIBE_URL' => '/photos/evrotsiklevka-parketa/index.php?action=SUBSCRIBE_PRODUCT&id=18455',
            'SUBSCRIBE_URL' => '/photos/evrotsiklevka-parketa/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18455',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 35927,
                    'SRC' => '/upload/iblock/896/896b72ca05ed251d8ec1507884b98cd1.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 35927,
                    'SRC' => '/upload/iblock/896/896b72ca05ed251d8ec1507884b98cd1.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 35927,
                    'SRC' => '/upload/iblock/896/896b72ca05ed251d8ec1507884b98cd1.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    4 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18456,
            '~ID' => '18456',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '345',
            '~XML_ID' => '345',
            'NAME' => '5',
            '~NAME' => '5',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '5',
            '~SORT' => '5',
            'PREVIEW_TEXT' => 'первый слой - грунтовка Bona универсальная, придает дубу янтарный оттенок
',
            '~PREVIEW_TEXT' => 'первый слой - грунтовка Bona универсальная, придает дубу янтарный оттенок
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1386',
            '~IBLOCK_SECTION_ID' => '1386',
            'DETAIL_PAGE_URL' => '/photos/evrotsiklevka-parketa/',
            '~DETAIL_PAGE_URL' => '/photos/evrotsiklevka-parketa/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 35928,
                    'SRC' => '/upload/iblock/592/5927254dfb9850c96dcf5c6f0d9a89fd.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '35928',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '345',
            '~EXTERNAL_ID' => '345',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/evrotsiklevka-parketa/index.php?action=BUY&id=18456',
            'BUY_URL' => '/photos/evrotsiklevka-parketa/index.php?action=BUY&amp;id=18456',
            '~ADD_URL' => '/photos/evrotsiklevka-parketa/index.php?action=ADD2BASKET&id=18456',
            'ADD_URL' => '/photos/evrotsiklevka-parketa/index.php?action=ADD2BASKET&amp;id=18456',
            '~SUBSCRIBE_URL' => '/photos/evrotsiklevka-parketa/index.php?action=SUBSCRIBE_PRODUCT&id=18456',
            'SUBSCRIBE_URL' => '/photos/evrotsiklevka-parketa/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18456',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 35928,
                    'SRC' => '/upload/iblock/592/5927254dfb9850c96dcf5c6f0d9a89fd.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 35928,
                    'SRC' => '/upload/iblock/592/5927254dfb9850c96dcf5c6f0d9a89fd.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 35928,
                    'SRC' => '/upload/iblock/592/5927254dfb9850c96dcf5c6f0d9a89fd.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    5 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18457,
            '~ID' => '18457',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '346',
            '~XML_ID' => '346',
            'NAME' => '6',
            '~NAME' => '6',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '6',
            '~SORT' => '6',
            'PREVIEW_TEXT' => '',
            '~PREVIEW_TEXT' => '',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1386',
            '~IBLOCK_SECTION_ID' => '1386',
            'DETAIL_PAGE_URL' => '/photos/evrotsiklevka-parketa/',
            '~DETAIL_PAGE_URL' => '/photos/evrotsiklevka-parketa/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 35929,
                    'SRC' => '/upload/iblock/d74/d7452a913daa7a934e4322863787b3fd.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '35929',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '346',
            '~EXTERNAL_ID' => '346',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/evrotsiklevka-parketa/index.php?action=BUY&id=18457',
            'BUY_URL' => '/photos/evrotsiklevka-parketa/index.php?action=BUY&amp;id=18457',
            '~ADD_URL' => '/photos/evrotsiklevka-parketa/index.php?action=ADD2BASKET&id=18457',
            'ADD_URL' => '/photos/evrotsiklevka-parketa/index.php?action=ADD2BASKET&amp;id=18457',
            '~SUBSCRIBE_URL' => '/photos/evrotsiklevka-parketa/index.php?action=SUBSCRIBE_PRODUCT&id=18457',
            'SUBSCRIBE_URL' => '/photos/evrotsiklevka-parketa/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18457',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 35929,
                    'SRC' => '/upload/iblock/d74/d7452a913daa7a934e4322863787b3fd.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 35929,
                    'SRC' => '/upload/iblock/d74/d7452a913daa7a934e4322863787b3fd.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 35929,
                    'SRC' => '/upload/iblock/d74/d7452a913daa7a934e4322863787b3fd.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    6 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18458,
            '~ID' => '18458',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '347',
            '~XML_ID' => '347',
            'NAME' => '7',
            '~NAME' => '7',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '7',
            '~SORT' => '7',
            'PREVIEW_TEXT' => '',
            '~PREVIEW_TEXT' => '',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1386',
            '~IBLOCK_SECTION_ID' => '1386',
            'DETAIL_PAGE_URL' => '/photos/evrotsiklevka-parketa/',
            '~DETAIL_PAGE_URL' => '/photos/evrotsiklevka-parketa/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 35930,
                    'SRC' => '/upload/iblock/6ca/6ca5bc7e715d4f9c75d78dba1bec0290.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '35930',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '347',
            '~EXTERNAL_ID' => '347',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/evrotsiklevka-parketa/index.php?action=BUY&id=18458',
            'BUY_URL' => '/photos/evrotsiklevka-parketa/index.php?action=BUY&amp;id=18458',
            '~ADD_URL' => '/photos/evrotsiklevka-parketa/index.php?action=ADD2BASKET&id=18458',
            'ADD_URL' => '/photos/evrotsiklevka-parketa/index.php?action=ADD2BASKET&amp;id=18458',
            '~SUBSCRIBE_URL' => '/photos/evrotsiklevka-parketa/index.php?action=SUBSCRIBE_PRODUCT&id=18458',
            'SUBSCRIBE_URL' => '/photos/evrotsiklevka-parketa/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18458',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 35930,
                    'SRC' => '/upload/iblock/6ca/6ca5bc7e715d4f9c75d78dba1bec0290.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 35930,
                    'SRC' => '/upload/iblock/6ca/6ca5bc7e715d4f9c75d78dba1bec0290.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 35930,
                    'SRC' => '/upload/iblock/6ca/6ca5bc7e715d4f9c75d78dba1bec0290.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    7 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18459,
            '~ID' => '18459',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '348',
            '~XML_ID' => '348',
            'NAME' => '8',
            '~NAME' => '8',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '8',
            '~SORT' => '8',
            'PREVIEW_TEXT' => '',
            '~PREVIEW_TEXT' => '',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1386',
            '~IBLOCK_SECTION_ID' => '1386',
            'DETAIL_PAGE_URL' => '/photos/evrotsiklevka-parketa/',
            '~DETAIL_PAGE_URL' => '/photos/evrotsiklevka-parketa/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 35931,
                    'SRC' => '/upload/iblock/0ad/0adbaaa62eb64a9a0adff9415373e4a7.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '35931',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '348',
            '~EXTERNAL_ID' => '348',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/evrotsiklevka-parketa/index.php?action=BUY&id=18459',
            'BUY_URL' => '/photos/evrotsiklevka-parketa/index.php?action=BUY&amp;id=18459',
            '~ADD_URL' => '/photos/evrotsiklevka-parketa/index.php?action=ADD2BASKET&id=18459',
            'ADD_URL' => '/photos/evrotsiklevka-parketa/index.php?action=ADD2BASKET&amp;id=18459',
            '~SUBSCRIBE_URL' => '/photos/evrotsiklevka-parketa/index.php?action=SUBSCRIBE_PRODUCT&id=18459',
            'SUBSCRIBE_URL' => '/photos/evrotsiklevka-parketa/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18459',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 35931,
                    'SRC' => '/upload/iblock/0ad/0adbaaa62eb64a9a0adff9415373e4a7.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 35931,
                    'SRC' => '/upload/iblock/0ad/0adbaaa62eb64a9a0adff9415373e4a7.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 35931,
                    'SRC' => '/upload/iblock/0ad/0adbaaa62eb64a9a0adff9415373e4a7.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    8 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18460,
            '~ID' => '18460',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '349',
            '~XML_ID' => '349',
            'NAME' => '9',
            '~NAME' => '9',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '9',
            '~SORT' => '9',
            'PREVIEW_TEXT' => 'три слоя лака Bona Traffic
',
            '~PREVIEW_TEXT' => 'три слоя лака Bona Traffic
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1386',
            '~IBLOCK_SECTION_ID' => '1386',
            'DETAIL_PAGE_URL' => '/photos/evrotsiklevka-parketa/',
            '~DETAIL_PAGE_URL' => '/photos/evrotsiklevka-parketa/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 35932,
                    'SRC' => '/upload/iblock/984/984366a45021c95b97dddb39f58a5147.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '35932',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '349',
            '~EXTERNAL_ID' => '349',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/evrotsiklevka-parketa/index.php?action=BUY&id=18460',
            'BUY_URL' => '/photos/evrotsiklevka-parketa/index.php?action=BUY&amp;id=18460',
            '~ADD_URL' => '/photos/evrotsiklevka-parketa/index.php?action=ADD2BASKET&id=18460',
            'ADD_URL' => '/photos/evrotsiklevka-parketa/index.php?action=ADD2BASKET&amp;id=18460',
            '~SUBSCRIBE_URL' => '/photos/evrotsiklevka-parketa/index.php?action=SUBSCRIBE_PRODUCT&id=18460',
            'SUBSCRIBE_URL' => '/photos/evrotsiklevka-parketa/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18460',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 35932,
                    'SRC' => '/upload/iblock/984/984366a45021c95b97dddb39f58a5147.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 35932,
                    'SRC' => '/upload/iblock/984/984366a45021c95b97dddb39f58a5147.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 35932,
                    'SRC' => '/upload/iblock/984/984366a45021c95b97dddb39f58a5147.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    9 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18461,
            '~ID' => '18461',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '350',
            '~XML_ID' => '350',
            'NAME' => '10',
            '~NAME' => '10',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '10',
            '~SORT' => '10',
            'PREVIEW_TEXT' => '',
            '~PREVIEW_TEXT' => '',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1386',
            '~IBLOCK_SECTION_ID' => '1386',
            'DETAIL_PAGE_URL' => '/photos/evrotsiklevka-parketa/',
            '~DETAIL_PAGE_URL' => '/photos/evrotsiklevka-parketa/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 35933,
                    'SRC' => '/upload/iblock/db7/db78fbd5102ba9183ece2d08971c2832.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '35933',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '350',
            '~EXTERNAL_ID' => '350',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/evrotsiklevka-parketa/index.php?action=BUY&id=18461',
            'BUY_URL' => '/photos/evrotsiklevka-parketa/index.php?action=BUY&amp;id=18461',
            '~ADD_URL' => '/photos/evrotsiklevka-parketa/index.php?action=ADD2BASKET&id=18461',
            'ADD_URL' => '/photos/evrotsiklevka-parketa/index.php?action=ADD2BASKET&amp;id=18461',
            '~SUBSCRIBE_URL' => '/photos/evrotsiklevka-parketa/index.php?action=SUBSCRIBE_PRODUCT&id=18461',
            'SUBSCRIBE_URL' => '/photos/evrotsiklevka-parketa/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18461',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 35933,
                    'SRC' => '/upload/iblock/db7/db78fbd5102ba9183ece2d08971c2832.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 35933,
                    'SRC' => '/upload/iblock/db7/db78fbd5102ba9183ece2d08971c2832.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 35933,
                    'SRC' => '/upload/iblock/db7/db78fbd5102ba9183ece2d08971c2832.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    10 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18462,
            '~ID' => '18462',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '351',
            '~XML_ID' => '351',
            'NAME' => '11',
            '~NAME' => '11',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '11',
            '~SORT' => '11',
            'PREVIEW_TEXT' => '',
            '~PREVIEW_TEXT' => '',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1386',
            '~IBLOCK_SECTION_ID' => '1386',
            'DETAIL_PAGE_URL' => '/photos/evrotsiklevka-parketa/',
            '~DETAIL_PAGE_URL' => '/photos/evrotsiklevka-parketa/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 35934,
                    'SRC' => '/upload/iblock/71d/71d84ab92eecc46553625df38a1720f1.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '35934',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '351',
            '~EXTERNAL_ID' => '351',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/evrotsiklevka-parketa/index.php?action=BUY&id=18462',
            'BUY_URL' => '/photos/evrotsiklevka-parketa/index.php?action=BUY&amp;id=18462',
            '~ADD_URL' => '/photos/evrotsiklevka-parketa/index.php?action=ADD2BASKET&id=18462',
            'ADD_URL' => '/photos/evrotsiklevka-parketa/index.php?action=ADD2BASKET&amp;id=18462',
            '~SUBSCRIBE_URL' => '/photos/evrotsiklevka-parketa/index.php?action=SUBSCRIBE_PRODUCT&id=18462',
            'SUBSCRIBE_URL' => '/photos/evrotsiklevka-parketa/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18462',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 35934,
                    'SRC' => '/upload/iblock/71d/71d84ab92eecc46553625df38a1720f1.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 35934,
                    'SRC' => '/upload/iblock/71d/71d84ab92eecc46553625df38a1720f1.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 35934,
                    'SRC' => '/upload/iblock/71d/71d84ab92eecc46553625df38a1720f1.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'Y',
        ),
);
