<?php

return array(
    0 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18474,
            '~ID' => '18474',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '363',
            '~XML_ID' => '363',
            'NAME' => '1',
            '~NAME' => '1',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '1',
            '~SORT' => '1',
            'PREVIEW_TEXT' => 'паркет уложен
',
            '~PREVIEW_TEXT' => 'паркет уложен
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1389',
            '~IBLOCK_SECTION_ID' => '1389',
            'DETAIL_PAGE_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/',
            '~DETAIL_PAGE_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 35946,
                    'SRC' => '/upload/iblock/005/0058c29a79edf475b5e05792d3ccf3bf.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '35946',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '363',
            '~EXTERNAL_ID' => '363',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=BUY&id=18474',
            'BUY_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=BUY&amp;id=18474',
            '~ADD_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=ADD2BASKET&id=18474',
            'ADD_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=ADD2BASKET&amp;id=18474',
            '~SUBSCRIBE_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=SUBSCRIBE_PRODUCT&id=18474',
            'SUBSCRIBE_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18474',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 35946,
                    'SRC' => '/upload/iblock/005/0058c29a79edf475b5e05792d3ccf3bf.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 35946,
                    'SRC' => '/upload/iblock/005/0058c29a79edf475b5e05792d3ccf3bf.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 35946,
                    'SRC' => '/upload/iblock/005/0058c29a79edf475b5e05792d3ccf3bf.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    1 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18475,
            '~ID' => '18475',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '364',
            '~XML_ID' => '364',
            'NAME' => '2',
            '~NAME' => '2',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '2',
            '~SORT' => '2',
            'PREVIEW_TEXT' => '',
            '~PREVIEW_TEXT' => '',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1389',
            '~IBLOCK_SECTION_ID' => '1389',
            'DETAIL_PAGE_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/',
            '~DETAIL_PAGE_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 35947,
                    'SRC' => '/upload/iblock/b98/b988d8cd93318b0e48d21b5286d3cd3e.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '35947',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '364',
            '~EXTERNAL_ID' => '364',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=BUY&id=18475',
            'BUY_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=BUY&amp;id=18475',
            '~ADD_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=ADD2BASKET&id=18475',
            'ADD_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=ADD2BASKET&amp;id=18475',
            '~SUBSCRIBE_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=SUBSCRIBE_PRODUCT&id=18475',
            'SUBSCRIBE_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18475',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 35947,
                    'SRC' => '/upload/iblock/b98/b988d8cd93318b0e48d21b5286d3cd3e.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 35947,
                    'SRC' => '/upload/iblock/b98/b988d8cd93318b0e48d21b5286d3cd3e.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 35947,
                    'SRC' => '/upload/iblock/b98/b988d8cd93318b0e48d21b5286d3cd3e.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    2 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18476,
            '~ID' => '18476',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '365',
            '~XML_ID' => '365',
            'NAME' => '3',
            '~NAME' => '3',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '3',
            '~SORT' => '3',
            'PREVIEW_TEXT' => 'паркет отшлифован и покрыт лаком Bona Traffic
',
            '~PREVIEW_TEXT' => 'паркет отшлифован и покрыт лаком Bona Traffic
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1389',
            '~IBLOCK_SECTION_ID' => '1389',
            'DETAIL_PAGE_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/',
            '~DETAIL_PAGE_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 35948,
                    'SRC' => '/upload/iblock/777/777ef41fc5f163d3eba3a74f5bd1ab26.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '35948',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '365',
            '~EXTERNAL_ID' => '365',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=BUY&id=18476',
            'BUY_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=BUY&amp;id=18476',
            '~ADD_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=ADD2BASKET&id=18476',
            'ADD_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=ADD2BASKET&amp;id=18476',
            '~SUBSCRIBE_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=SUBSCRIBE_PRODUCT&id=18476',
            'SUBSCRIBE_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18476',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 35948,
                    'SRC' => '/upload/iblock/777/777ef41fc5f163d3eba3a74f5bd1ab26.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 35948,
                    'SRC' => '/upload/iblock/777/777ef41fc5f163d3eba3a74f5bd1ab26.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 35948,
                    'SRC' => '/upload/iblock/777/777ef41fc5f163d3eba3a74f5bd1ab26.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    3 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18477,
            '~ID' => '18477',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '366',
            '~XML_ID' => '366',
            'NAME' => '4',
            '~NAME' => '4',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '4',
            '~SORT' => '4',
            'PREVIEW_TEXT' => '',
            '~PREVIEW_TEXT' => '',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1389',
            '~IBLOCK_SECTION_ID' => '1389',
            'DETAIL_PAGE_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/',
            '~DETAIL_PAGE_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 35949,
                    'SRC' => '/upload/iblock/ed4/ed42e894204933aa52e72c19de87005d.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '35949',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '366',
            '~EXTERNAL_ID' => '366',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=BUY&id=18477',
            'BUY_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=BUY&amp;id=18477',
            '~ADD_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=ADD2BASKET&id=18477',
            'ADD_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=ADD2BASKET&amp;id=18477',
            '~SUBSCRIBE_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=SUBSCRIBE_PRODUCT&id=18477',
            'SUBSCRIBE_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18477',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 35949,
                    'SRC' => '/upload/iblock/ed4/ed42e894204933aa52e72c19de87005d.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 35949,
                    'SRC' => '/upload/iblock/ed4/ed42e894204933aa52e72c19de87005d.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 35949,
                    'SRC' => '/upload/iblock/ed4/ed42e894204933aa52e72c19de87005d.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    4 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18478,
            '~ID' => '18478',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '367',
            '~XML_ID' => '367',
            'NAME' => '5',
            '~NAME' => '5',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '5',
            '~SORT' => '5',
            'PREVIEW_TEXT' => '',
            '~PREVIEW_TEXT' => '',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1389',
            '~IBLOCK_SECTION_ID' => '1389',
            'DETAIL_PAGE_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/',
            '~DETAIL_PAGE_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 35950,
                    'SRC' => '/upload/iblock/f4f/f4f6551cbc485a048a254272d966eb46.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '35950',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '367',
            '~EXTERNAL_ID' => '367',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=BUY&id=18478',
            'BUY_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=BUY&amp;id=18478',
            '~ADD_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=ADD2BASKET&id=18478',
            'ADD_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=ADD2BASKET&amp;id=18478',
            '~SUBSCRIBE_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=SUBSCRIBE_PRODUCT&id=18478',
            'SUBSCRIBE_URL' => '/photos/evrotsiklevka-khudozhestvennogo-parketa/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18478',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 35950,
                    'SRC' => '/upload/iblock/f4f/f4f6551cbc485a048a254272d966eb46.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 35950,
                    'SRC' => '/upload/iblock/f4f/f4f6551cbc485a048a254272d966eb46.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 35950,
                    'SRC' => '/upload/iblock/f4f/f4f6551cbc485a048a254272d966eb46.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'Y',
        ),
);
