<?php

return array(
    0 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18489,
            '~ID' => '18489',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '379',
            '~XML_ID' => '379',
            'NAME' => '1',
            '~NAME' => '1',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '1',
            '~SORT' => '1',
            'PREVIEW_TEXT' => 'укладка паркетной доски(орех) на фанерное основание предоставленное заказчиком
',
            '~PREVIEW_TEXT' => 'укладка паркетной доски(орех) на фанерное основание предоставленное заказчиком
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1391',
            '~IBLOCK_SECTION_ID' => '1391',
            'DETAIL_PAGE_URL' => '/photos/ukladka-parketnoy-doski/',
            '~DETAIL_PAGE_URL' => '/photos/ukladka-parketnoy-doski/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 35961,
                    'SRC' => '/upload/iblock/192/19298894a575ecf8690c0c7048b2460a.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '35961',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '379',
            '~EXTERNAL_ID' => '379',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=BUY&id=18489',
            'BUY_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=BUY&amp;id=18489',
            '~ADD_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=ADD2BASKET&id=18489',
            'ADD_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=ADD2BASKET&amp;id=18489',
            '~SUBSCRIBE_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=SUBSCRIBE_PRODUCT&id=18489',
            'SUBSCRIBE_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18489',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 35961,
                    'SRC' => '/upload/iblock/192/19298894a575ecf8690c0c7048b2460a.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 35961,
                    'SRC' => '/upload/iblock/192/19298894a575ecf8690c0c7048b2460a.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 35961,
                    'SRC' => '/upload/iblock/192/19298894a575ecf8690c0c7048b2460a.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    1 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18490,
            '~ID' => '18490',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '380',
            '~XML_ID' => '380',
            'NAME' => '2',
            '~NAME' => '2',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '2',
            '~SORT' => '2',
            'PREVIEW_TEXT' => 'заказчик предупрежден, что фанерное основание положено с грубыми нарушениями
',
            '~PREVIEW_TEXT' => 'заказчик предупрежден, что фанерное основание положено с грубыми нарушениями
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1391',
            '~IBLOCK_SECTION_ID' => '1391',
            'DETAIL_PAGE_URL' => '/photos/ukladka-parketnoy-doski/',
            '~DETAIL_PAGE_URL' => '/photos/ukladka-parketnoy-doski/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 35962,
                    'SRC' => '/upload/iblock/080/080150b1b2108eb317f9ff7aa514b3a7.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '35962',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '380',
            '~EXTERNAL_ID' => '380',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=BUY&id=18490',
            'BUY_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=BUY&amp;id=18490',
            '~ADD_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=ADD2BASKET&id=18490',
            'ADD_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=ADD2BASKET&amp;id=18490',
            '~SUBSCRIBE_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=SUBSCRIBE_PRODUCT&id=18490',
            'SUBSCRIBE_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18490',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 35962,
                    'SRC' => '/upload/iblock/080/080150b1b2108eb317f9ff7aa514b3a7.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 35962,
                    'SRC' => '/upload/iblock/080/080150b1b2108eb317f9ff7aa514b3a7.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 35962,
                    'SRC' => '/upload/iblock/080/080150b1b2108eb317f9ff7aa514b3a7.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    2 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18491,
            '~ID' => '18491',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '381',
            '~XML_ID' => '381',
            'NAME' => '3',
            '~NAME' => '3',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '3',
            '~SORT' => '3',
            'PREVIEW_TEXT' => '',
            '~PREVIEW_TEXT' => '',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1391',
            '~IBLOCK_SECTION_ID' => '1391',
            'DETAIL_PAGE_URL' => '/photos/ukladka-parketnoy-doski/',
            '~DETAIL_PAGE_URL' => '/photos/ukladka-parketnoy-doski/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 35963,
                    'SRC' => '/upload/iblock/f88/f88a11ff8de4c5379729a03f5104b2de.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '35963',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '381',
            '~EXTERNAL_ID' => '381',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=BUY&id=18491',
            'BUY_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=BUY&amp;id=18491',
            '~ADD_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=ADD2BASKET&id=18491',
            'ADD_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=ADD2BASKET&amp;id=18491',
            '~SUBSCRIBE_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=SUBSCRIBE_PRODUCT&id=18491',
            'SUBSCRIBE_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18491',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 35963,
                    'SRC' => '/upload/iblock/f88/f88a11ff8de4c5379729a03f5104b2de.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 35963,
                    'SRC' => '/upload/iblock/f88/f88a11ff8de4c5379729a03f5104b2de.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 35963,
                    'SRC' => '/upload/iblock/f88/f88a11ff8de4c5379729a03f5104b2de.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    3 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18492,
            '~ID' => '18492',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '382',
            '~XML_ID' => '382',
            'NAME' => '4',
            '~NAME' => '4',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '4',
            '~SORT' => '4',
            'PREVIEW_TEXT' => 'на границе с плиткой пробковый компенсатор
',
            '~PREVIEW_TEXT' => 'на границе с плиткой пробковый компенсатор
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1391',
            '~IBLOCK_SECTION_ID' => '1391',
            'DETAIL_PAGE_URL' => '/photos/ukladka-parketnoy-doski/',
            '~DETAIL_PAGE_URL' => '/photos/ukladka-parketnoy-doski/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 35964,
                    'SRC' => '/upload/iblock/25d/25d12ac0993b53ab6c7c29f09cd4f835.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '35964',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '382',
            '~EXTERNAL_ID' => '382',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=BUY&id=18492',
            'BUY_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=BUY&amp;id=18492',
            '~ADD_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=ADD2BASKET&id=18492',
            'ADD_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=ADD2BASKET&amp;id=18492',
            '~SUBSCRIBE_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=SUBSCRIBE_PRODUCT&id=18492',
            'SUBSCRIBE_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18492',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 35964,
                    'SRC' => '/upload/iblock/25d/25d12ac0993b53ab6c7c29f09cd4f835.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 35964,
                    'SRC' => '/upload/iblock/25d/25d12ac0993b53ab6c7c29f09cd4f835.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 35964,
                    'SRC' => '/upload/iblock/25d/25d12ac0993b53ab6c7c29f09cd4f835.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    4 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18493,
            '~ID' => '18493',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '383',
            '~XML_ID' => '383',
            'NAME' => '5',
            '~NAME' => '5',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '5',
            '~SORT' => '5',
            'PREVIEW_TEXT' => '',
            '~PREVIEW_TEXT' => '',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1391',
            '~IBLOCK_SECTION_ID' => '1391',
            'DETAIL_PAGE_URL' => '/photos/ukladka-parketnoy-doski/',
            '~DETAIL_PAGE_URL' => '/photos/ukladka-parketnoy-doski/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 35965,
                    'SRC' => '/upload/iblock/27b/27b61a171e167ffc0f8bd6f9df6c0145.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '35965',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '383',
            '~EXTERNAL_ID' => '383',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=BUY&id=18493',
            'BUY_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=BUY&amp;id=18493',
            '~ADD_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=ADD2BASKET&id=18493',
            'ADD_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=ADD2BASKET&amp;id=18493',
            '~SUBSCRIBE_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=SUBSCRIBE_PRODUCT&id=18493',
            'SUBSCRIBE_URL' => '/photos/ukladka-parketnoy-doski/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18493',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 35965,
                    'SRC' => '/upload/iblock/27b/27b61a171e167ffc0f8bd6f9df6c0145.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 35965,
                    'SRC' => '/upload/iblock/27b/27b61a171e167ffc0f8bd6f9df6c0145.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 35965,
                    'SRC' => '/upload/iblock/27b/27b61a171e167ffc0f8bd6f9df6c0145.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'Y',
        ),
);
