<?php

return array(
    0 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18566,
            '~ID' => '18566',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '456',
            '~XML_ID' => '456',
            'NAME' => '1',
            '~NAME' => '1',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '1',
            '~SORT' => '1',
            'PREVIEW_TEXT' => 'Типичный паркет в сталинском доме.
',
            '~PREVIEW_TEXT' => 'Типичный паркет в сталинском доме.
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1398',
            '~IBLOCK_SECTION_ID' => '1398',
            'DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            '~DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 36038,
                    'SRC' => '/upload/iblock/405/4058f0d3630e983ae48efff3e5142d6c.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '36038',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '456',
            '~EXTERNAL_ID' => '456',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&id=18566',
            'BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&amp;id=18566',
            '~ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&id=18566',
            'ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&amp;id=18566',
            '~SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&id=18566',
            'SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18566',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 36038,
                    'SRC' => '/upload/iblock/405/4058f0d3630e983ae48efff3e5142d6c.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 36038,
                    'SRC' => '/upload/iblock/405/4058f0d3630e983ae48efff3e5142d6c.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 36038,
                    'SRC' => '/upload/iblock/405/4058f0d3630e983ae48efff3e5142d6c.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    1 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18567,
            '~ID' => '18567',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '457',
            '~XML_ID' => '457',
            'NAME' => '2',
            '~NAME' => '2',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '2',
            '~SORT' => '2',
            'PREVIEW_TEXT' => 'После демонтажа старого плинтуса открылась неприятная картина. Наличие гвоздей, гигантские щели.
',
            '~PREVIEW_TEXT' => 'После демонтажа старого плинтуса открылась неприятная картина. Наличие гвоздей, гигантские щели.
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1398',
            '~IBLOCK_SECTION_ID' => '1398',
            'DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            '~DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 36039,
                    'SRC' => '/upload/iblock/89b/89b39782af9793448679fba7b1bb4952.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '36039',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '457',
            '~EXTERNAL_ID' => '457',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&id=18567',
            'BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&amp;id=18567',
            '~ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&id=18567',
            'ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&amp;id=18567',
            '~SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&id=18567',
            'SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18567',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 36039,
                    'SRC' => '/upload/iblock/89b/89b39782af9793448679fba7b1bb4952.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 36039,
                    'SRC' => '/upload/iblock/89b/89b39782af9793448679fba7b1bb4952.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 36039,
                    'SRC' => '/upload/iblock/89b/89b39782af9793448679fba7b1bb4952.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    2 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18568,
            '~ID' => '18568',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '458',
            '~XML_ID' => '458',
            'NAME' => '3',
            '~NAME' => '3',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '3',
            '~SORT' => '3',
            'PREVIEW_TEXT' => 'Примыкание паркета со стеной обескураживает.
',
            '~PREVIEW_TEXT' => 'Примыкание паркета со стеной обескураживает.
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1398',
            '~IBLOCK_SECTION_ID' => '1398',
            'DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            '~DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 36040,
                    'SRC' => '/upload/iblock/9fa/9fa965e94d3f03cbc77ebb3e22ce3f94.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '36040',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '458',
            '~EXTERNAL_ID' => '458',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&id=18568',
            'BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&amp;id=18568',
            '~ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&id=18568',
            'ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&amp;id=18568',
            '~SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&id=18568',
            'SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18568',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 36040,
                    'SRC' => '/upload/iblock/9fa/9fa965e94d3f03cbc77ebb3e22ce3f94.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 36040,
                    'SRC' => '/upload/iblock/9fa/9fa965e94d3f03cbc77ebb3e22ce3f94.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 36040,
                    'SRC' => '/upload/iblock/9fa/9fa965e94d3f03cbc77ebb3e22ce3f94.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    3 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18569,
            '~ID' => '18569',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '459',
            '~XML_ID' => '459',
            'NAME' => '4',
            '~NAME' => '4',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '4',
            '~SORT' => '4',
            'PREVIEW_TEXT' => 'Современные плинтуса не в состоянии скрыть подобное безобразие.
',
            '~PREVIEW_TEXT' => 'Современные плинтуса не в состоянии скрыть подобное безобразие.
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1398',
            '~IBLOCK_SECTION_ID' => '1398',
            'DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            '~DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 36041,
                    'SRC' => '/upload/iblock/7fb/7fb3979f66a7cbb2f21b3424c082206f.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '36041',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '459',
            '~EXTERNAL_ID' => '459',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&id=18569',
            'BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&amp;id=18569',
            '~ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&id=18569',
            'ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&amp;id=18569',
            '~SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&id=18569',
            'SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18569',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 36041,
                    'SRC' => '/upload/iblock/7fb/7fb3979f66a7cbb2f21b3424c082206f.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 36041,
                    'SRC' => '/upload/iblock/7fb/7fb3979f66a7cbb2f21b3424c082206f.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 36041,
                    'SRC' => '/upload/iblock/7fb/7fb3979f66a7cbb2f21b3424c082206f.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    4 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18570,
            '~ID' => '18570',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '460',
            '~XML_ID' => '460',
            'NAME' => '5',
            '~NAME' => '5',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '5',
            '~SORT' => '5',
            'PREVIEW_TEXT' => 'Комбинация неровных стен и огромных щелей делает задачу установки шпонированного европлинтуса невыполнимой.
',
            '~PREVIEW_TEXT' => 'Комбинация неровных стен и огромных щелей делает задачу установки шпонированного европлинтуса невыполнимой.
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1398',
            '~IBLOCK_SECTION_ID' => '1398',
            'DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            '~DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 36042,
                    'SRC' => '/upload/iblock/5d2/5d2b2f49776ef36c34fbfeec09bac15d.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '36042',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '460',
            '~EXTERNAL_ID' => '460',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&id=18570',
            'BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&amp;id=18570',
            '~ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&id=18570',
            'ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&amp;id=18570',
            '~SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&id=18570',
            'SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18570',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 36042,
                    'SRC' => '/upload/iblock/5d2/5d2b2f49776ef36c34fbfeec09bac15d.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 36042,
                    'SRC' => '/upload/iblock/5d2/5d2b2f49776ef36c34fbfeec09bac15d.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 36042,
                    'SRC' => '/upload/iblock/5d2/5d2b2f49776ef36c34fbfeec09bac15d.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    5 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18571,
            '~ID' => '18571',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '461',
            '~XML_ID' => '461',
            'NAME' => '6',
            '~NAME' => '6',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '6',
            '~SORT' => '6',
            'PREVIEW_TEXT' => 'Но, найдено техническое решение - уложить фриз по периметру паркета. Можно применить породу дерева, отличную от основной кладки. Выбор расцветки и породы дерева для фриза за Вами.
',
            '~PREVIEW_TEXT' => 'Но, найдено техническое решение - уложить фриз по периметру паркета. Можно применить породу дерева, отличную от основной кладки. Выбор расцветки и породы дерева для фриза за Вами.
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1398',
            '~IBLOCK_SECTION_ID' => '1398',
            'DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            '~DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 36043,
                    'SRC' => '/upload/iblock/0d0/0d0566a9483c568f92bc695255238cf3.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '36043',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '461',
            '~EXTERNAL_ID' => '461',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&id=18571',
            'BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&amp;id=18571',
            '~ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&id=18571',
            'ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&amp;id=18571',
            '~SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&id=18571',
            'SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18571',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 36043,
                    'SRC' => '/upload/iblock/0d0/0d0566a9483c568f92bc695255238cf3.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 36043,
                    'SRC' => '/upload/iblock/0d0/0d0566a9483c568f92bc695255238cf3.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 36043,
                    'SRC' => '/upload/iblock/0d0/0d0566a9483c568f92bc695255238cf3.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    6 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18572,
            '~ID' => '18572',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '462',
            '~XML_ID' => '462',
            'NAME' => '7',
            '~NAME' => '7',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '7',
            '~SORT' => '7',
            'PREVIEW_TEXT' => 'Углы пришлось полностью реставрировать.
',
            '~PREVIEW_TEXT' => 'Углы пришлось полностью реставрировать.
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1398',
            '~IBLOCK_SECTION_ID' => '1398',
            'DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            '~DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 36044,
                    'SRC' => '/upload/iblock/eb0/eb0e05e3dc204edddc1f78830ca74e40.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '36044',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '462',
            '~EXTERNAL_ID' => '462',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&id=18572',
            'BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&amp;id=18572',
            '~ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&id=18572',
            'ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&amp;id=18572',
            '~SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&id=18572',
            'SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18572',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 36044,
                    'SRC' => '/upload/iblock/eb0/eb0e05e3dc204edddc1f78830ca74e40.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 36044,
                    'SRC' => '/upload/iblock/eb0/eb0e05e3dc204edddc1f78830ca74e40.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 36044,
                    'SRC' => '/upload/iblock/eb0/eb0e05e3dc204edddc1f78830ca74e40.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    7 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18573,
            '~ID' => '18573',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '463',
            '~XML_ID' => '463',
            'NAME' => '8',
            '~NAME' => '8',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '8',
            '~SORT' => '8',
            'PREVIEW_TEXT' => 'После ремонта и установки фриза угол преобразился.
',
            '~PREVIEW_TEXT' => 'После ремонта и установки фриза угол преобразился.
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1398',
            '~IBLOCK_SECTION_ID' => '1398',
            'DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            '~DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 36045,
                    'SRC' => '/upload/iblock/ce5/ce51e4ee22f858ac20419872856276bb.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '36045',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '463',
            '~EXTERNAL_ID' => '463',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&id=18573',
            'BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&amp;id=18573',
            '~ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&id=18573',
            'ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&amp;id=18573',
            '~SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&id=18573',
            'SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18573',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 36045,
                    'SRC' => '/upload/iblock/ce5/ce51e4ee22f858ac20419872856276bb.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 36045,
                    'SRC' => '/upload/iblock/ce5/ce51e4ee22f858ac20419872856276bb.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 36045,
                    'SRC' => '/upload/iblock/ce5/ce51e4ee22f858ac20419872856276bb.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    8 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18574,
            '~ID' => '18574',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '464',
            '~XML_ID' => '464',
            'NAME' => '9',
            '~NAME' => '9',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '9',
            '~SORT' => '9',
            'PREVIEW_TEXT' => 'Перекладывать пришлось все углы.
',
            '~PREVIEW_TEXT' => 'Перекладывать пришлось все углы.
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1398',
            '~IBLOCK_SECTION_ID' => '1398',
            'DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            '~DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 36046,
                    'SRC' => '/upload/iblock/9cb/9cb0c00997270f1c5aad703fd89c05d6.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '36046',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '464',
            '~EXTERNAL_ID' => '464',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&id=18574',
            'BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&amp;id=18574',
            '~ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&id=18574',
            'ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&amp;id=18574',
            '~SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&id=18574',
            'SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18574',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 36046,
                    'SRC' => '/upload/iblock/9cb/9cb0c00997270f1c5aad703fd89c05d6.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 36046,
                    'SRC' => '/upload/iblock/9cb/9cb0c00997270f1c5aad703fd89c05d6.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 36046,
                    'SRC' => '/upload/iblock/9cb/9cb0c00997270f1c5aad703fd89c05d6.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    9 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18575,
            '~ID' => '18575',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '465',
            '~XML_ID' => '465',
            'NAME' => '10',
            '~NAME' => '10',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '10',
            '~SORT' => '10',
            'PREVIEW_TEXT' => 'Иногда требуется замена поврежденных плашек.
',
            '~PREVIEW_TEXT' => 'Иногда требуется замена поврежденных плашек.
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1398',
            '~IBLOCK_SECTION_ID' => '1398',
            'DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            '~DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 36047,
                    'SRC' => '/upload/iblock/dc9/dc9f4af6fe79e250d6ceee3fdc115dc0.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '36047',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '465',
            '~EXTERNAL_ID' => '465',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&id=18575',
            'BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&amp;id=18575',
            '~ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&id=18575',
            'ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&amp;id=18575',
            '~SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&id=18575',
            'SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18575',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 36047,
                    'SRC' => '/upload/iblock/dc9/dc9f4af6fe79e250d6ceee3fdc115dc0.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 36047,
                    'SRC' => '/upload/iblock/dc9/dc9f4af6fe79e250d6ceee3fdc115dc0.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 36047,
                    'SRC' => '/upload/iblock/dc9/dc9f4af6fe79e250d6ceee3fdc115dc0.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    10 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18576,
            '~ID' => '18576',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '466',
            '~XML_ID' => '466',
            'NAME' => '11',
            '~NAME' => '11',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '11',
            '~SORT' => '11',
            'PREVIEW_TEXT' => 'Паркетный пол преображается.
',
            '~PREVIEW_TEXT' => 'Паркетный пол преображается.
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1398',
            '~IBLOCK_SECTION_ID' => '1398',
            'DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            '~DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 36048,
                    'SRC' => '/upload/iblock/ee3/ee3b31f9e5af225255506ff9185ee1ae.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '36048',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '466',
            '~EXTERNAL_ID' => '466',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&id=18576',
            'BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&amp;id=18576',
            '~ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&id=18576',
            'ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&amp;id=18576',
            '~SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&id=18576',
            'SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18576',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 36048,
                    'SRC' => '/upload/iblock/ee3/ee3b31f9e5af225255506ff9185ee1ae.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 36048,
                    'SRC' => '/upload/iblock/ee3/ee3b31f9e5af225255506ff9185ee1ae.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 36048,
                    'SRC' => '/upload/iblock/ee3/ee3b31f9e5af225255506ff9185ee1ae.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    11 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18577,
            '~ID' => '18577',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '467',
            '~XML_ID' => '467',
            'NAME' => '12',
            '~NAME' => '12',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '12',
            '~SORT' => '12',
            'PREVIEW_TEXT' => 'Тяжело представить, как выглядел паркет до ремонта. Плинтус установлен по евростандарту: очень аккуратно в углах, нет щелей под плинтусом.
',
            '~PREVIEW_TEXT' => 'Тяжело представить, как выглядел паркет до ремонта. Плинтус установлен по евростандарту: очень аккуратно в углах, нет щелей под плинтусом.
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1398',
            '~IBLOCK_SECTION_ID' => '1398',
            'DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            '~DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 36049,
                    'SRC' => '/upload/iblock/916/916660547af8e6a2083cf23fff14fc88.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '36049',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '467',
            '~EXTERNAL_ID' => '467',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&id=18577',
            'BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&amp;id=18577',
            '~ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&id=18577',
            'ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&amp;id=18577',
            '~SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&id=18577',
            'SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18577',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 36049,
                    'SRC' => '/upload/iblock/916/916660547af8e6a2083cf23fff14fc88.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 36049,
                    'SRC' => '/upload/iblock/916/916660547af8e6a2083cf23fff14fc88.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 36049,
                    'SRC' => '/upload/iblock/916/916660547af8e6a2083cf23fff14fc88.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    12 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18578,
            '~ID' => '18578',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '468',
            '~XML_ID' => '468',
            'NAME' => '13',
            '~NAME' => '13',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '13',
            '~SORT' => '13',
            'PREVIEW_TEXT' => 'Плинтус плотно прилегает к стенам, не смотря на кривизну поверхности.
',
            '~PREVIEW_TEXT' => 'Плинтус плотно прилегает к стенам, не смотря на кривизну поверхности.
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1398',
            '~IBLOCK_SECTION_ID' => '1398',
            'DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            '~DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 36050,
                    'SRC' => '/upload/iblock/49e/49e1b570d4f782fbe2e28736e3e2fc33.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '36050',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '468',
            '~EXTERNAL_ID' => '468',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&id=18578',
            'BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&amp;id=18578',
            '~ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&id=18578',
            'ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&amp;id=18578',
            '~SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&id=18578',
            'SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18578',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 36050,
                    'SRC' => '/upload/iblock/49e/49e1b570d4f782fbe2e28736e3e2fc33.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 36050,
                    'SRC' => '/upload/iblock/49e/49e1b570d4f782fbe2e28736e3e2fc33.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 36050,
                    'SRC' => '/upload/iblock/49e/49e1b570d4f782fbe2e28736e3e2fc33.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    13 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18579,
            '~ID' => '18579',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '469',
            '~XML_ID' => '469',
            'NAME' => '14',
            '~NAME' => '14',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '14',
            '~SORT' => '14',
            'PREVIEW_TEXT' => 'Паркет заиграл новыми красками.
',
            '~PREVIEW_TEXT' => 'Паркет заиграл новыми красками.
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1398',
            '~IBLOCK_SECTION_ID' => '1398',
            'DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            '~DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 36051,
                    'SRC' => '/upload/iblock/6e4/6e4ef418aa84c50b1f9838b593e47c00.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '36051',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '469',
            '~EXTERNAL_ID' => '469',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&id=18579',
            'BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&amp;id=18579',
            '~ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&id=18579',
            'ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&amp;id=18579',
            '~SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&id=18579',
            'SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18579',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 36051,
                    'SRC' => '/upload/iblock/6e4/6e4ef418aa84c50b1f9838b593e47c00.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 36051,
                    'SRC' => '/upload/iblock/6e4/6e4ef418aa84c50b1f9838b593e47c00.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 36051,
                    'SRC' => '/upload/iblock/6e4/6e4ef418aa84c50b1f9838b593e47c00.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    14 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18580,
            '~ID' => '18580',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '470',
            '~XML_ID' => '470',
            'NAME' => '15',
            '~NAME' => '15',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '15',
            '~SORT' => '15',
            'PREVIEW_TEXT' => 'Проведенные работы изменили пол до неузнаваемости. Ремонт паркета значительно дешевле полной замены пола. Обновленный паркет прослужит ещё очень долго.
',
            '~PREVIEW_TEXT' => 'Проведенные работы изменили пол до неузнаваемости. Ремонт паркета значительно дешевле полной замены пола. Обновленный паркет прослужит ещё очень долго.
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1398',
            '~IBLOCK_SECTION_ID' => '1398',
            'DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            '~DETAIL_PAGE_URL' => '/photos/remont-parketa-po-perimetru/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 36052,
                    'SRC' => '/upload/iblock/a73/a73681f0e903e597d7f4daa1633953a4.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '36052',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '470',
            '~EXTERNAL_ID' => '470',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&id=18580',
            'BUY_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=BUY&amp;id=18580',
            '~ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&id=18580',
            'ADD_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=ADD2BASKET&amp;id=18580',
            '~SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&id=18580',
            'SUBSCRIBE_URL' => '/photos/remont-parketa-po-perimetru/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18580',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 36052,
                    'SRC' => '/upload/iblock/a73/a73681f0e903e597d7f4daa1633953a4.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 36052,
                    'SRC' => '/upload/iblock/a73/a73681f0e903e597d7f4daa1633953a4.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 36052,
                    'SRC' => '/upload/iblock/a73/a73681f0e903e597d7f4daa1633953a4.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'Y',
        ),
);
