<?php

return array(
    0 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18587,
            '~ID' => '18587',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '477',
            '~XML_ID' => '477',
            'NAME' => '1',
            '~NAME' => '1',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '1',
            '~SORT' => '1',
            'PREVIEW_TEXT' => 'ПОСЛЕ ЗАМЕНЫ ДВЕРНОЙ КОРОБКИ НЕОБХОДИМО СОБЛЮДАЯ РИСУНОК, ЗАЛОЖИТЬ ОБРАЗОВАВШИЕСЯ ПУСТОТЫ ПАРКЕТОМ ',
            '~PREVIEW_TEXT' => 'ПОСЛЕ ЗАМЕНЫ ДВЕРНОЙ КОРОБКИ НЕОБХОДИМО СОБЛЮДАЯ РИСУНОК, ЗАЛОЖИТЬ ОБРАЗОВАВШИЕСЯ ПУСТОТЫ ПАРКЕТОМ ',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '2',
            '~MODIFIED_BY' => '2',
            'IBLOCK_SECTION_ID' => '1400',
            '~IBLOCK_SECTION_ID' => '1400',
            'DETAIL_PAGE_URL' => '/photos/remont-parketa/',
            '~DETAIL_PAGE_URL' => '/photos/remont-parketa/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 36059,
                    'SRC' => '/upload/iblock/e52/e52337a32aa7643b8ce49d5c900f5395.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '36059',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '477',
            '~EXTERNAL_ID' => '477',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/remont-parketa/index.php?action=BUY&id=18587',
            'BUY_URL' => '/photos/remont-parketa/index.php?action=BUY&amp;id=18587',
            '~ADD_URL' => '/photos/remont-parketa/index.php?action=ADD2BASKET&id=18587',
            'ADD_URL' => '/photos/remont-parketa/index.php?action=ADD2BASKET&amp;id=18587',
            '~SUBSCRIBE_URL' => '/photos/remont-parketa/index.php?action=SUBSCRIBE_PRODUCT&id=18587',
            'SUBSCRIBE_URL' => '/photos/remont-parketa/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18587',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 36059,
                    'SRC' => '/upload/iblock/e52/e52337a32aa7643b8ce49d5c900f5395.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 36059,
                    'SRC' => '/upload/iblock/e52/e52337a32aa7643b8ce49d5c900f5395.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 36059,
                    'SRC' => '/upload/iblock/e52/e52337a32aa7643b8ce49d5c900f5395.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    1 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18588,
            '~ID' => '18588',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '478',
            '~XML_ID' => '478',
            'NAME' => '2',
            '~NAME' => '2',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '2',
            '~SORT' => '2',
            'PREVIEW_TEXT' => 'ПРИ НЕОБХОДИМОСТИ МЕНЯЮТСЯ ПОВРЕЖДЕНЫЕ ПАРКЕТНЫЕ ПЛАШКИ НА НОВЫЕ
',
            '~PREVIEW_TEXT' => 'ПРИ НЕОБХОДИМОСТИ МЕНЯЮТСЯ ПОВРЕЖДЕНЫЕ ПАРКЕТНЫЕ ПЛАШКИ НА НОВЫЕ
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1400',
            '~IBLOCK_SECTION_ID' => '1400',
            'DETAIL_PAGE_URL' => '/photos/remont-parketa/',
            '~DETAIL_PAGE_URL' => '/photos/remont-parketa/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 36060,
                    'SRC' => '/upload/iblock/6b5/6b51d299268e9ceae6ba2c949f941f3f.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '36060',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '478',
            '~EXTERNAL_ID' => '478',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/remont-parketa/index.php?action=BUY&id=18588',
            'BUY_URL' => '/photos/remont-parketa/index.php?action=BUY&amp;id=18588',
            '~ADD_URL' => '/photos/remont-parketa/index.php?action=ADD2BASKET&id=18588',
            'ADD_URL' => '/photos/remont-parketa/index.php?action=ADD2BASKET&amp;id=18588',
            '~SUBSCRIBE_URL' => '/photos/remont-parketa/index.php?action=SUBSCRIBE_PRODUCT&id=18588',
            'SUBSCRIBE_URL' => '/photos/remont-parketa/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18588',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 36060,
                    'SRC' => '/upload/iblock/6b5/6b51d299268e9ceae6ba2c949f941f3f.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 36060,
                    'SRC' => '/upload/iblock/6b5/6b51d299268e9ceae6ba2c949f941f3f.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 36060,
                    'SRC' => '/upload/iblock/6b5/6b51d299268e9ceae6ba2c949f941f3f.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    2 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18589,
            '~ID' => '18589',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '479',
            '~XML_ID' => '479',
            'NAME' => '3',
            '~NAME' => '3',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '3',
            '~SORT' => '3',
            'PREVIEW_TEXT' => 'НЕСТАНДАРТНЫЕ РАЗМЕРЫ ВЫПИЛВАЮТСЯ НА МЕСТЕ ИЗ МАССИВА ПАРКЕТА
',
            '~PREVIEW_TEXT' => 'НЕСТАНДАРТНЫЕ РАЗМЕРЫ ВЫПИЛВАЮТСЯ НА МЕСТЕ ИЗ МАССИВА ПАРКЕТА
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1400',
            '~IBLOCK_SECTION_ID' => '1400',
            'DETAIL_PAGE_URL' => '/photos/remont-parketa/',
            '~DETAIL_PAGE_URL' => '/photos/remont-parketa/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 36061,
                    'SRC' => '/upload/iblock/61c/61cca67b1eb1a5bc4f6cabf9dc6b8df1.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '36061',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '479',
            '~EXTERNAL_ID' => '479',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/remont-parketa/index.php?action=BUY&id=18589',
            'BUY_URL' => '/photos/remont-parketa/index.php?action=BUY&amp;id=18589',
            '~ADD_URL' => '/photos/remont-parketa/index.php?action=ADD2BASKET&id=18589',
            'ADD_URL' => '/photos/remont-parketa/index.php?action=ADD2BASKET&amp;id=18589',
            '~SUBSCRIBE_URL' => '/photos/remont-parketa/index.php?action=SUBSCRIBE_PRODUCT&id=18589',
            'SUBSCRIBE_URL' => '/photos/remont-parketa/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18589',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 36061,
                    'SRC' => '/upload/iblock/61c/61cca67b1eb1a5bc4f6cabf9dc6b8df1.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 36061,
                    'SRC' => '/upload/iblock/61c/61cca67b1eb1a5bc4f6cabf9dc6b8df1.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 36061,
                    'SRC' => '/upload/iblock/61c/61cca67b1eb1a5bc4f6cabf9dc6b8df1.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    3 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18590,
            '~ID' => '18590',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '480',
            '~XML_ID' => '480',
            'NAME' => '4',
            '~NAME' => '4',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '4',
            '~SORT' => '4',
            'PREVIEW_TEXT' => '',
            '~PREVIEW_TEXT' => '',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1400',
            '~IBLOCK_SECTION_ID' => '1400',
            'DETAIL_PAGE_URL' => '/photos/remont-parketa/',
            '~DETAIL_PAGE_URL' => '/photos/remont-parketa/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 36062,
                    'SRC' => '/upload/iblock/06c/06c6f826603cee092a683055f7e4da26.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '36062',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '480',
            '~EXTERNAL_ID' => '480',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/remont-parketa/index.php?action=BUY&id=18590',
            'BUY_URL' => '/photos/remont-parketa/index.php?action=BUY&amp;id=18590',
            '~ADD_URL' => '/photos/remont-parketa/index.php?action=ADD2BASKET&id=18590',
            'ADD_URL' => '/photos/remont-parketa/index.php?action=ADD2BASKET&amp;id=18590',
            '~SUBSCRIBE_URL' => '/photos/remont-parketa/index.php?action=SUBSCRIBE_PRODUCT&id=18590',
            'SUBSCRIBE_URL' => '/photos/remont-parketa/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18590',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 36062,
                    'SRC' => '/upload/iblock/06c/06c6f826603cee092a683055f7e4da26.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 36062,
                    'SRC' => '/upload/iblock/06c/06c6f826603cee092a683055f7e4da26.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 36062,
                    'SRC' => '/upload/iblock/06c/06c6f826603cee092a683055f7e4da26.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    4 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18591,
            '~ID' => '18591',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '481',
            '~XML_ID' => '481',
            'NAME' => '5',
            '~NAME' => '5',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '5',
            '~SORT' => '5',
            'PREVIEW_TEXT' => 'ПЕРЕБОРКА ПАРКЕТА ПОСЛЕ ЗАТОПЛЕНИЯ
',
            '~PREVIEW_TEXT' => 'ПЕРЕБОРКА ПАРКЕТА ПОСЛЕ ЗАТОПЛЕНИЯ
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1400',
            '~IBLOCK_SECTION_ID' => '1400',
            'DETAIL_PAGE_URL' => '/photos/remont-parketa/',
            '~DETAIL_PAGE_URL' => '/photos/remont-parketa/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 36063,
                    'SRC' => '/upload/iblock/e93/e936c0d850e1c9654918deb64d7c1345.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '36063',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '481',
            '~EXTERNAL_ID' => '481',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/remont-parketa/index.php?action=BUY&id=18591',
            'BUY_URL' => '/photos/remont-parketa/index.php?action=BUY&amp;id=18591',
            '~ADD_URL' => '/photos/remont-parketa/index.php?action=ADD2BASKET&id=18591',
            'ADD_URL' => '/photos/remont-parketa/index.php?action=ADD2BASKET&amp;id=18591',
            '~SUBSCRIBE_URL' => '/photos/remont-parketa/index.php?action=SUBSCRIBE_PRODUCT&id=18591',
            'SUBSCRIBE_URL' => '/photos/remont-parketa/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18591',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 36063,
                    'SRC' => '/upload/iblock/e93/e936c0d850e1c9654918deb64d7c1345.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 36063,
                    'SRC' => '/upload/iblock/e93/e936c0d850e1c9654918deb64d7c1345.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 36063,
                    'SRC' => '/upload/iblock/e93/e936c0d850e1c9654918deb64d7c1345.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    5 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18592,
            '~ID' => '18592',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '482',
            '~XML_ID' => '482',
            'NAME' => '6',
            '~NAME' => '6',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '6',
            '~SORT' => '6',
            'PREVIEW_TEXT' => '',
            '~PREVIEW_TEXT' => '',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1400',
            '~IBLOCK_SECTION_ID' => '1400',
            'DETAIL_PAGE_URL' => '/photos/remont-parketa/',
            '~DETAIL_PAGE_URL' => '/photos/remont-parketa/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 36064,
                    'SRC' => '/upload/iblock/575/5750f418e938296c1c2359fab93b0a8f.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '36064',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '482',
            '~EXTERNAL_ID' => '482',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/remont-parketa/index.php?action=BUY&id=18592',
            'BUY_URL' => '/photos/remont-parketa/index.php?action=BUY&amp;id=18592',
            '~ADD_URL' => '/photos/remont-parketa/index.php?action=ADD2BASKET&id=18592',
            'ADD_URL' => '/photos/remont-parketa/index.php?action=ADD2BASKET&amp;id=18592',
            '~SUBSCRIBE_URL' => '/photos/remont-parketa/index.php?action=SUBSCRIBE_PRODUCT&id=18592',
            'SUBSCRIBE_URL' => '/photos/remont-parketa/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18592',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 36064,
                    'SRC' => '/upload/iblock/575/5750f418e938296c1c2359fab93b0a8f.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 36064,
                    'SRC' => '/upload/iblock/575/5750f418e938296c1c2359fab93b0a8f.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 36064,
                    'SRC' => '/upload/iblock/575/5750f418e938296c1c2359fab93b0a8f.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'N',
        ),
    6 =>
        array(
            'PRICES' =>
                array(),
            'PRICE_MATRIX' => false,
            'MIN_PRICE' => false,
            'ID' => 18593,
            '~ID' => '18593',
            'IBLOCK_ID' => 39,
            '~IBLOCK_ID' => '39',
            'CODE' => '',
            '~CODE' => '',
            'XML_ID' => '483',
            '~XML_ID' => '483',
            'NAME' => '7',
            '~NAME' => '7',
            'ACTIVE' => 'Y',
            '~ACTIVE' => 'Y',
            'DATE_ACTIVE_FROM' => NULL,
            '~DATE_ACTIVE_FROM' => NULL,
            'DATE_ACTIVE_TO' => NULL,
            '~DATE_ACTIVE_TO' => NULL,
            'SORT' => '7',
            '~SORT' => '7',
            'PREVIEW_TEXT' => 'ПОСЛЕ ПЕРЕБОРКИ НЕОБХОДИМА ЦИКЛЕВКА ПОМЕЩЕНИЯ
',
            '~PREVIEW_TEXT' => 'ПОСЛЕ ПЕРЕБОРКИ НЕОБХОДИМА ЦИКЛЕВКА ПОМЕЩЕНИЯ
',
            'PREVIEW_TEXT_TYPE' => 'html',
            '~PREVIEW_TEXT_TYPE' => 'html',
            'DETAIL_TEXT' => '',
            '~DETAIL_TEXT' => '',
            'DETAIL_TEXT_TYPE' => 'html',
            '~DETAIL_TEXT_TYPE' => 'html',
            'DATE_CREATE' => '00.00.0000 00:00:00',
            '~DATE_CREATE' => '00.00.0000 00:00:00',
            'CREATED_BY' => '1',
            '~CREATED_BY' => '1',
            'TAGS' => '',
            '~TAGS' => '',
            'TIMESTAMP_X' => '00.00.0000 00:00:00',
            '~TIMESTAMP_X' => '00.00.0000 00:00:00',
            'MODIFIED_BY' => '1',
            '~MODIFIED_BY' => '1',
            'IBLOCK_SECTION_ID' => '1400',
            '~IBLOCK_SECTION_ID' => '1400',
            'DETAIL_PAGE_URL' => '/photos/remont-parketa/',
            '~DETAIL_PAGE_URL' => '/photos/remont-parketa/',
            'DETAIL_PICTURE' => NULL,
            '~DETAIL_PICTURE' => NULL,
            'PREVIEW_PICTURE' =>
                array(
                    'ID' => 36065,
                    'SRC' => '/upload/iblock/893/893f704548445f9a9ce28a1b549451cc.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            '~PREVIEW_PICTURE' => '36065',
            'LANG_DIR' => '/',
            '~LANG_DIR' => '/',
            'EXTERNAL_ID' => '483',
            '~EXTERNAL_ID' => '483',
            'IBLOCK_TYPE_ID' => 'content',
            '~IBLOCK_TYPE_ID' => 'content',
            'IBLOCK_CODE' => 'photos',
            '~IBLOCK_CODE' => 'photos',
            'IBLOCK_EXTERNAL_ID' => NULL,
            '~IBLOCK_EXTERNAL_ID' => NULL,
            'LID' => 's1',
            '~LID' => 's1',
            'ACTIVE_FROM' => NULL,
            'ACTIVE_TO' => NULL,
            'IPROPERTY_VALUES' =>
                array(
                    'SECTION_META_TITLE' => 'фотографии паркетных работ',
                ),
            'PRODUCT' =>
                array(
                    'TYPE' => NULL,
                    'AVAILABLE' => NULL,
                    'MEASURE' => NULL,
                    'VAT_ID' => NULL,
                    'VAT_RATE' => NULL,
                    'VAT_INCLUDED' => NULL,
                    'QUANTITY' => NULL,
                    'QUANTITY_TRACE' => NULL,
                    'CAN_BUY_ZERO' => NULL,
                    'SUBSCRIPTION' => NULL,
                    'BUNDLE' => NULL,
                ),
            'PROPERTIES' =>
                array(),
            'DISPLAY_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES' =>
                array(),
            'PRODUCT_PROPERTIES_FILL' =>
                array(),
            'OFFERS' =>
                array(),
            'OFFER_ID_SELECTED' => 0,
            'ITEM_PRICE_MODE' => NULL,
            'ITEM_PRICES' =>
                array(),
            'ITEM_QUANTITY_RANGES' => NULL,
            'ITEM_MEASURE_RATIOS' => NULL,
            'ITEM_MEASURE' =>
                array(),
            'ITEM_MEASURE_RATIO_SELECTED' => NULL,
            'ITEM_QUANTITY_RANGE_SELECTED' => NULL,
            'ITEM_PRICE_SELECTED' => NULL,
            'CAN_BUY' => false,
            'EDIT_LINK' => NULL,
            'DELETE_LINK' => NULL,
            'SECTION' =>
                array(
                    'PATH' =>
                        array(),
                ),
            '~BUY_URL' => '/photos/remont-parketa/index.php?action=BUY&id=18593',
            'BUY_URL' => '/photos/remont-parketa/index.php?action=BUY&amp;id=18593',
            '~ADD_URL' => '/photos/remont-parketa/index.php?action=ADD2BASKET&id=18593',
            'ADD_URL' => '/photos/remont-parketa/index.php?action=ADD2BASKET&amp;id=18593',
            '~SUBSCRIBE_URL' => '/photos/remont-parketa/index.php?action=SUBSCRIBE_PRODUCT&id=18593',
            'SUBSCRIBE_URL' => '/photos/remont-parketa/index.php?action=SUBSCRIBE_PRODUCT&amp;id=18593',
            'CATALOG_MEASURE_NAME' => NULL,
            '~CATALOG_MEASURE_NAME' => NULL,
            'CATALOG_MEASURE_RATIO' => 1,
            'CHECK_QUANTITY' => false,
            'CATALOG_QUANTITY' => 0,
            'CATALOG' => true,
            'CATALOG_SUBSCRIPTION' => 'N',
            'LABEL' => false,
            'LABEL_VALUE' => '',
            'LABEL_ARRAY_VALUE' =>
                array(),
            'PREVIEW_PICTURE_SECOND' =>
                array(
                    'ID' => 36065,
                    'SRC' => '/upload/iblock/893/893f704548445f9a9ce28a1b549451cc.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'SECOND_PICT' => true,
            'PRODUCT_PREVIEW' =>
                array(
                    'ID' => 36065,
                    'SRC' => '/upload/iblock/893/893f704548445f9a9ce28a1b549451cc.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'PRODUCT_PREVIEW_SECOND' =>
                array(
                    'ID' => 36065,
                    'SRC' => '/upload/iblock/893/893f704548445f9a9ce28a1b549451cc.jpg',
                    'WIDTH' => 800,
                    'HEIGHT' => 600,
                ),
            'CATALOG_TYPE' => 1,
            'LAST_ELEMENT' => 'Y',
        ),
);
