<?php

return array (
  0 =>
  array (
    'ID' => 1809,
    'NAME' => 'Stauf Velourrolle - валик для масла-воска',
    'CATALOG_PRICE_1' => NULL,
    'CATALOG_CURRENCY_1' => NULL,
    'ITEM_PRICES' =>
    array (
      0 =>
      array (
        'UNROUND_BASE_PRICE' => 1095.1766,
        'UNROUND_PRICE' => 1095.1766,
        'BASE_PRICE' => 1095.1766,
        'PRICE' => 1095.1766,
        'ID' => '1898',
        'PRICE_TYPE_ID' => '1',
        'CURRENCY' => 'RUB',
        'DISCOUNT' => 0,
        'PERCENT' => 0,
        'QUANTITY_FROM' => NULL,
        'QUANTITY_TO' => NULL,
        'QUANTITY_HASH' => 'ZERO-INF',
        'MEASURE_RATIO_ID' => NULL,
        'PRINT_BASE_PRICE' => '1 095 р',
        'RATIO_BASE_PRICE' => 1095.1766,
        'PRINT_RATIO_BASE_PRICE' => '1 095 р',
        'PRINT_PRICE' => '1 095 р',
        'RATIO_PRICE' => 1095.1766,
        'PRINT_RATIO_PRICE' => '1 095 р',
        'PRINT_DISCOUNT' => '0 р',
        'RATIO_DISCOUNT' => 0,
        'PRINT_RATIO_DISCOUNT' => '0 р',
        'MIN_QUANTITY' => 1,
      ),
    ),
    'OFFERS' =>
    array (
    ),
  ),
  1 =>
  array (
    'ID' => 1800,
    'NAME' => 'Stauf Nylon Lackrolle - валик для лаков на рстворителях',
    'CATALOG_PRICE_1' => NULL,
    'CATALOG_CURRENCY_1' => NULL,
    'ITEM_PRICES' =>
    array (
      0 =>
      array (
        'UNROUND_BASE_PRICE' => 1173.4035,
        'UNROUND_PRICE' => 1173.4035,
        'BASE_PRICE' => 1173.4035,
        'PRICE' => 1173.4035,
        'ID' => '1892',
        'PRICE_TYPE_ID' => '1',
        'CURRENCY' => 'RUB',
        'DISCOUNT' => 0,
        'PERCENT' => 0,
        'QUANTITY_FROM' => NULL,
        'QUANTITY_TO' => NULL,
        'QUANTITY_HASH' => 'ZERO-INF',
        'MEASURE_RATIO_ID' => NULL,
        'PRINT_BASE_PRICE' => '1 173 р',
        'RATIO_BASE_PRICE' => 1173.4035,
        'PRINT_RATIO_BASE_PRICE' => '1 173 р',
        'PRINT_PRICE' => '1 173 р',
        'RATIO_PRICE' => 1173.4035,
        'PRINT_RATIO_PRICE' => '1 173 р',
        'PRINT_DISCOUNT' => '0 р',
        'RATIO_DISCOUNT' => 0,
        'PRINT_RATIO_DISCOUNT' => '0 р',
        'MIN_QUANTITY' => 1,
      ),
    ),
    'OFFERS' =>
    array (
    ),
  ),
  2 =>
  array (
    'ID' => 1798,
    'NAME' => 'Stauf Grundierrolle - валик для грунтовок',
    'CATALOG_PRICE_1' => NULL,
    'CATALOG_CURRENCY_1' => NULL,
    'ITEM_PRICES' =>
    array (
      0 =>
      array (
        'UNROUND_BASE_PRICE' => 1095.1766,
        'UNROUND_PRICE' => 1095.1766,
        'BASE_PRICE' => 1095.1766,
        'PRICE' => 1095.1766,
        'ID' => '1890',
        'PRICE_TYPE_ID' => '1',
        'CURRENCY' => 'RUB',
        'DISCOUNT' => 0,
        'PERCENT' => 0,
        'QUANTITY_FROM' => NULL,
        'QUANTITY_TO' => NULL,
        'QUANTITY_HASH' => 'ZERO-INF',
        'MEASURE_RATIO_ID' => NULL,
        'PRINT_BASE_PRICE' => '1 095 р',
        'RATIO_BASE_PRICE' => 1095.1766,
        'PRINT_RATIO_BASE_PRICE' => '1 095 р',
        'PRINT_PRICE' => '1 095 р',
        'RATIO_PRICE' => 1095.1766,
        'PRINT_RATIO_PRICE' => '1 095 р',
        'PRINT_DISCOUNT' => '0 р',
        'RATIO_DISCOUNT' => 0,
        'PRINT_RATIO_DISCOUNT' => '0 р',
        'MIN_QUANTITY' => 1,
      ),
    ),
    'OFFERS' =>
    array (
    ),
  ),
  3 =>
  array (
    'ID' => 1796,
    'NAME' => 'Stauf Microfaserrolle',
    'CATALOG_PRICE_1' => NULL,
    'CATALOG_CURRENCY_1' => NULL,
    'ITEM_PRICES' =>
    array (
      0 =>
      array (
        'UNROUND_BASE_PRICE' => 1329.8573000000001,
        'UNROUND_PRICE' => 1329.8573000000001,
        'BASE_PRICE' => 1329.8573000000001,
        'PRICE' => 1329.8573000000001,
        'ID' => '1888',
        'PRICE_TYPE_ID' => '1',
        'CURRENCY' => 'RUB',
        'DISCOUNT' => 0,
        'PERCENT' => 0,
        'QUANTITY_FROM' => NULL,
        'QUANTITY_TO' => NULL,
        'QUANTITY_HASH' => 'ZERO-INF',
        'MEASURE_RATIO_ID' => NULL,
        'PRINT_BASE_PRICE' => '1 330 р',
        'RATIO_BASE_PRICE' => 1329.8573000000001,
        'PRINT_RATIO_BASE_PRICE' => '1 330 р',
        'PRINT_PRICE' => '1 330 р',
        'RATIO_PRICE' => 1329.8573000000001,
        'PRINT_RATIO_PRICE' => '1 330 р',
        'PRINT_DISCOUNT' => '0 р',
        'RATIO_DISCOUNT' => 0,
        'PRINT_RATIO_DISCOUNT' => '0 р',
        'MIN_QUANTITY' => 1,
      ),
    ),
    'OFFERS' =>
    array (
    ),
  ),
  4 =>
  array (
    'ID' => 286,
    'NAME' => 'Валик Lobadur Microfaser 60-80',
    'CATALOG_PRICE_1' => NULL,
    'CATALOG_CURRENCY_1' => NULL,
    'ITEM_PRICES' =>
    array (
      0 =>
      array (
        'UNROUND_BASE_PRICE' => 850.0,
        'UNROUND_PRICE' => 850.0,
        'BASE_PRICE' => 850.0,
        'PRICE' => 850.0,
        'ID' => '65',
        'PRICE_TYPE_ID' => '1',
        'CURRENCY' => 'RUB',
        'DISCOUNT' => 0,
        'PERCENT' => 0,
        'QUANTITY_FROM' => NULL,
        'QUANTITY_TO' => NULL,
        'QUANTITY_HASH' => 'ZERO-INF',
        'MEASURE_RATIO_ID' => NULL,
        'PRINT_BASE_PRICE' => '850 р',
        'RATIO_BASE_PRICE' => 850.0,
        'PRINT_RATIO_BASE_PRICE' => '850 р',
        'PRINT_PRICE' => '850 р',
        'RATIO_PRICE' => 850.0,
        'PRINT_RATIO_PRICE' => '850 р',
        'PRINT_DISCOUNT' => '0 р',
        'RATIO_DISCOUNT' => 0,
        'PRINT_RATIO_DISCOUNT' => '0 р',
        'MIN_QUANTITY' => 1,
      ),
    ),
    'OFFERS' =>
    array (
    ),
  ),
  5 =>
  array (
    'ID' => 293,
    'NAME' => 'Кисть-щётка для нанесения масла',
    'CATALOG_PRICE_1' => NULL,
    'CATALOG_CURRENCY_1' => NULL,
    'ITEM_PRICES' =>
    array (
      0 =>
      array (
        'UNROUND_BASE_PRICE' => 5100.3938800000005,
        'UNROUND_PRICE' => 5100.3938800000005,
        'BASE_PRICE' => 5100.3938800000005,
        'PRICE' => 5100.3938800000005,
        'ID' => '68',
        'PRICE_TYPE_ID' => '1',
        'CURRENCY' => 'RUB',
        'DISCOUNT' => 0,
        'PERCENT' => 0,
        'QUANTITY_FROM' => NULL,
        'QUANTITY_TO' => NULL,
        'QUANTITY_HASH' => 'ZERO-INF',
        'MEASURE_RATIO_ID' => NULL,
        'PRINT_BASE_PRICE' => '5 100 р',
        'RATIO_BASE_PRICE' => 5100.3938800000005,
        'PRINT_RATIO_BASE_PRICE' => '5 100 р',
        'PRINT_PRICE' => '5 100 р',
        'RATIO_PRICE' => 5100.3938800000005,
        'PRINT_RATIO_PRICE' => '5 100 р',
        'PRINT_DISCOUNT' => '0 р',
        'RATIO_DISCOUNT' => 0,
        'PRINT_RATIO_DISCOUNT' => '0 р',
        'MIN_QUANTITY' => 1,
      ),
    ),
    'OFFERS' =>
    array (
    ),
  ),
  6 =>
  array (
    'ID' => 284,
    'NAME' => 'Шпатель сдвоенный',
    'CATALOG_PRICE_1' => NULL,
    'CATALOG_CURRENCY_1' => NULL,
    'ITEM_PRICES' =>
    array (
    ),
    'OFFERS' =>
    array (
      0 =>
      array (
        'ID' => 11172,
        '~ID' => '11172',
        'IBLOCK_ID' => 17,
        '~IBLOCK_ID' => '17',
        'PROPERTY_343_VALUE' => '284',
        '~PROPERTY_343_VALUE' => '284',
        'PROPERTY_343_VALUE_ID' => '11172:343',
        '~PROPERTY_343_VALUE_ID' => '11172:343',
        'SORT' => '500',
        '~SORT' => '500',
        'PREVIEW_PICTURE' => NULL,
        '~PREVIEW_PICTURE' => NULL,
        'DETAIL_PICTURE' => NULL,
        '~DETAIL_PICTURE' => NULL,
        'CATALOG_QUANTITY' => '1',
        '~CATALOG_QUANTITY' => '1',
        'CATALOG_QUANTITY_RESERVED' => '0',
        '~CATALOG_QUANTITY_RESERVED' => '0',
        'CATALOG_QUANTITY_TRACE' => 'N',
        '~CATALOG_QUANTITY_TRACE' => 'N',
        'CATALOG_QUANTITY_TRACE_ORIG' => 'D',
        '~CATALOG_QUANTITY_TRACE_ORIG' => 'D',
        'CATALOG_CAN_BUY_ZERO' => 'Y',
        '~CATALOG_CAN_BUY_ZERO' => 'Y',
        'CATALOG_CAN_BUY_ZERO_ORIG' => 'D',
        '~CATALOG_CAN_BUY_ZERO_ORIG' => 'D',
        'CATALOG_NEGATIVE_AMOUNT_TRACE' => 'Y',
        '~CATALOG_NEGATIVE_AMOUNT_TRACE' => 'Y',
        'CATALOG_NEGATIVE_AMOUNT_ORIG' => 'D',
        '~CATALOG_NEGATIVE_AMOUNT_ORIG' => 'D',
        'CATALOG_SUBSCRIBE' => 'Y',
        '~CATALOG_SUBSCRIBE' => 'Y',
        'CATALOG_SUBSCRIBE_ORIG' => 'D',
        '~CATALOG_SUBSCRIBE_ORIG' => 'D',
        'CATALOG_AVAILABLE' => 'Y',
        '~CATALOG_AVAILABLE' => 'Y',
        'CATALOG_WEIGHT' => '0',
        '~CATALOG_WEIGHT' => '0',
        'CATALOG_WIDTH' => '0',
        '~CATALOG_WIDTH' => '0',
        'CATALOG_LENGTH' => '0',
        '~CATALOG_LENGTH' => '0',
        'CATALOG_HEIGHT' => '0',
        '~CATALOG_HEIGHT' => '0',
        'CATALOG_MEASURE' => 5,
        '~CATALOG_MEASURE' => '5',
        'CATALOG_VAT' => NULL,
        '~CATALOG_VAT' => NULL,
        'CATALOG_VAT_ID' => '0',
        '~CATALOG_VAT_ID' => '0',
        'CATALOG_VAT_INCLUDED' => 'N',
        '~CATALOG_VAT_INCLUDED' => 'N',
        'CATALOG_PRICE_TYPE' => 'S',
        '~CATALOG_PRICE_TYPE' => 'S',
        'CATALOG_RECUR_SCHEME_TYPE' => 'D',
        '~CATALOG_RECUR_SCHEME_TYPE' => 'D',
        'CATALOG_RECUR_SCHEME_LENGTH' => '0',
        '~CATALOG_RECUR_SCHEME_LENGTH' => '0',
        'CATALOG_TRIAL_PRICE_ID' => NULL,
        '~CATALOG_TRIAL_PRICE_ID' => NULL,
        'CATALOG_WITHOUT_ORDER' => 'N',
        '~CATALOG_WITHOUT_ORDER' => 'N',
        'CATALOG_SELECT_BEST_PRICE' => 'Y',
        '~CATALOG_SELECT_BEST_PRICE' => 'Y',
        'CATALOG_PURCHASING_PRICE' => '0.00',
        '~CATALOG_PURCHASING_PRICE' => '0.00',
        'CATALOG_PURCHASING_CURRENCY' => 'EUR',
        '~CATALOG_PURCHASING_CURRENCY' => 'EUR',
        'CATALOG_TYPE' => 4,
        '~CATALOG_TYPE' => '4',
        'CATALOG_BUNDLE' => 'N',
        '~CATALOG_BUNDLE' => 'N',
        'SORT_HASH' => '55a05e0c64b1da4d5b3b5ae83ebd371e',
        'LINK_ELEMENT_ID' => 284,
        'PROPERTIES' =>
        array (
        ),
        'DISPLAY_PROPERTIES' =>
        array (
        ),
        'PRODUCT' =>
        array (
          'TYPE' => 4,
          'AVAILABLE' => 'Y',
          'MEASURE' => 5,
          'VAT_ID' => NULL,
          'VAT_RATE' => NULL,
          'VAT_INCLUDED' => 'N',
          'QUANTITY' => '1',
          'QUANTITY_TRACE' => 'N',
          'CAN_BUY_ZERO' => 'Y',
          'SUBSCRIPTION' => NULL,
          'BUNDLE' => 'N',
        ),
        'ITEM_PRICE_MODE' => 'S',
        'ITEM_PRICES' =>
        array (
          0 =>
          array (
            'UNROUND_BASE_PRICE' => 2033.8994,
            'UNROUND_PRICE' => 2033.8994,
            'BASE_PRICE' => 2033.8994,
            'PRICE' => 2033.8994,
            'ID' => '4261',
            'PRICE_TYPE_ID' => '1',
            'CURRENCY' => 'RUB',
            'DISCOUNT' => 0,
            'PERCENT' => 0,
            'QUANTITY_FROM' => NULL,
            'QUANTITY_TO' => NULL,
            'QUANTITY_HASH' => 'ZERO-INF',
            'MEASURE_RATIO_ID' => NULL,
            'PRINT_BASE_PRICE' => '2 034 р',
            'RATIO_BASE_PRICE' => 2033.8994,
            'PRINT_RATIO_BASE_PRICE' => '2 034 р',
            'PRINT_PRICE' => '2 034 р',
            'RATIO_PRICE' => 2033.8994,
            'PRINT_RATIO_PRICE' => '2 034 р',
            'PRINT_DISCOUNT' => '0 р',
            'RATIO_DISCOUNT' => 0,
            'PRINT_RATIO_DISCOUNT' => '0 р',
            'MIN_QUANTITY' => 1,
          ),
        ),
        'ITEM_QUANTITY_RANGES' =>
        array (
          'ZERO-INF' =>
          array (
            'HASH' => 'ZERO-INF',
            'QUANTITY_FROM' => NULL,
            'QUANTITY_TO' => NULL,
            'SORT_FROM' => 0,
            'SORT_TO' => INF,
          ),
        ),
        'ITEM_MEASURE_RATIOS' =>
        array (
          866 =>
          array (
            'ID' => 866,
            'RATIO' => 1,
            'IS_DEFAULT' => 'Y',
            'PRODUCT_ID' => '11172',
          ),
        ),
        'ITEM_MEASURE' =>
        array (
          'ID' => 5,
          'TITLE' => 'шт',
          '~TITLE' => 'шт',
        ),
        'ITEM_MEASURE_RATIO_SELECTED' => 866,
        'ITEM_QUANTITY_RANGE_SELECTED' => 'ZERO-INF',
        'ITEM_PRICE_SELECTED' => 0,
        'CHECK_QUANTITY' => false,
        'CAN_BUY' => true,
        'ITEM_PRICES_CAN_BUY' => true,
      ),
      1 =>
      array (
        'ID' => 11173,
        '~ID' => '11173',
        'IBLOCK_ID' => 17,
        '~IBLOCK_ID' => '17',
        'PROPERTY_343_VALUE' => '284',
        '~PROPERTY_343_VALUE' => '284',
        'PROPERTY_343_VALUE_ID' => '11173:343',
        '~PROPERTY_343_VALUE_ID' => '11173:343',
        'SORT' => '501',
        '~SORT' => '501',
        'PREVIEW_PICTURE' => NULL,
        '~PREVIEW_PICTURE' => NULL,
        'DETAIL_PICTURE' => NULL,
        '~DETAIL_PICTURE' => NULL,
        'CATALOG_QUANTITY' => '1',
        '~CATALOG_QUANTITY' => '1',
        'CATALOG_QUANTITY_RESERVED' => '0',
        '~CATALOG_QUANTITY_RESERVED' => '0',
        'CATALOG_QUANTITY_TRACE' => 'N',
        '~CATALOG_QUANTITY_TRACE' => 'N',
        'CATALOG_QUANTITY_TRACE_ORIG' => 'D',
        '~CATALOG_QUANTITY_TRACE_ORIG' => 'D',
        'CATALOG_CAN_BUY_ZERO' => 'Y',
        '~CATALOG_CAN_BUY_ZERO' => 'Y',
        'CATALOG_CAN_BUY_ZERO_ORIG' => 'D',
        '~CATALOG_CAN_BUY_ZERO_ORIG' => 'D',
        'CATALOG_NEGATIVE_AMOUNT_TRACE' => 'Y',
        '~CATALOG_NEGATIVE_AMOUNT_TRACE' => 'Y',
        'CATALOG_NEGATIVE_AMOUNT_ORIG' => 'D',
        '~CATALOG_NEGATIVE_AMOUNT_ORIG' => 'D',
        'CATALOG_SUBSCRIBE' => 'Y',
        '~CATALOG_SUBSCRIBE' => 'Y',
        'CATALOG_SUBSCRIBE_ORIG' => 'D',
        '~CATALOG_SUBSCRIBE_ORIG' => 'D',
        'CATALOG_AVAILABLE' => 'Y',
        '~CATALOG_AVAILABLE' => 'Y',
        'CATALOG_WEIGHT' => '0',
        '~CATALOG_WEIGHT' => '0',
        'CATALOG_WIDTH' => '0',
        '~CATALOG_WIDTH' => '0',
        'CATALOG_LENGTH' => '0',
        '~CATALOG_LENGTH' => '0',
        'CATALOG_HEIGHT' => '0',
        '~CATALOG_HEIGHT' => '0',
        'CATALOG_MEASURE' => 5,
        '~CATALOG_MEASURE' => '5',
        'CATALOG_VAT' => NULL,
        '~CATALOG_VAT' => NULL,
        'CATALOG_VAT_ID' => '0',
        '~CATALOG_VAT_ID' => '0',
        'CATALOG_VAT_INCLUDED' => 'N',
        '~CATALOG_VAT_INCLUDED' => 'N',
        'CATALOG_PRICE_TYPE' => 'S',
        '~CATALOG_PRICE_TYPE' => 'S',
        'CATALOG_RECUR_SCHEME_TYPE' => 'D',
        '~CATALOG_RECUR_SCHEME_TYPE' => 'D',
        'CATALOG_RECUR_SCHEME_LENGTH' => '0',
        '~CATALOG_RECUR_SCHEME_LENGTH' => '0',
        'CATALOG_TRIAL_PRICE_ID' => NULL,
        '~CATALOG_TRIAL_PRICE_ID' => NULL,
        'CATALOG_WITHOUT_ORDER' => 'N',
        '~CATALOG_WITHOUT_ORDER' => 'N',
        'CATALOG_SELECT_BEST_PRICE' => 'Y',
        '~CATALOG_SELECT_BEST_PRICE' => 'Y',
        'CATALOG_PURCHASING_PRICE' => '0.00',
        '~CATALOG_PURCHASING_PRICE' => '0.00',
        'CATALOG_PURCHASING_CURRENCY' => 'EUR',
        '~CATALOG_PURCHASING_CURRENCY' => 'EUR',
        'CATALOG_TYPE' => 4,
        '~CATALOG_TYPE' => '4',
        'CATALOG_BUNDLE' => 'N',
        '~CATALOG_BUNDLE' => 'N',
        'SORT_HASH' => '0cad7f1efd6a51d30f404b51237fab09',
        'LINK_ELEMENT_ID' => 284,
        'PROPERTIES' =>
        array (
        ),
        'DISPLAY_PROPERTIES' =>
        array (
        ),
        'PRODUCT' =>
        array (
          'TYPE' => 4,
          'AVAILABLE' => 'Y',
          'MEASURE' => 5,
          'VAT_ID' => NULL,
          'VAT_RATE' => NULL,
          'VAT_INCLUDED' => 'N',
          'QUANTITY' => '1',
          'QUANTITY_TRACE' => 'N',
          'CAN_BUY_ZERO' => 'Y',
          'SUBSCRIPTION' => NULL,
          'BUNDLE' => 'N',
        ),
        'ITEM_PRICE_MODE' => 'S',
        'ITEM_PRICES' =>
        array (
          0 =>
          array (
            'UNROUND_BASE_PRICE' => 2201.304966,
            'UNROUND_PRICE' => 2201.304966,
            'BASE_PRICE' => 2201.304966,
            'PRICE' => 2201.304966,
            'ID' => '4262',
            'PRICE_TYPE_ID' => '1',
            'CURRENCY' => 'RUB',
            'DISCOUNT' => 0,
            'PERCENT' => 0,
            'QUANTITY_FROM' => NULL,
            'QUANTITY_TO' => NULL,
            'QUANTITY_HASH' => 'ZERO-INF',
            'MEASURE_RATIO_ID' => NULL,
            'PRINT_BASE_PRICE' => '2 201 р',
            'RATIO_BASE_PRICE' => 2201.304966,
            'PRINT_RATIO_BASE_PRICE' => '2 201 р',
            'PRINT_PRICE' => '2 201 р',
            'RATIO_PRICE' => 2201.304966,
            'PRINT_RATIO_PRICE' => '2 201 р',
            'PRINT_DISCOUNT' => '0 р',
            'RATIO_DISCOUNT' => 0,
            'PRINT_RATIO_DISCOUNT' => '0 р',
            'MIN_QUANTITY' => 1,
          ),
        ),
        'ITEM_QUANTITY_RANGES' =>
        array (
          'ZERO-INF' =>
          array (
            'HASH' => 'ZERO-INF',
            'QUANTITY_FROM' => NULL,
            'QUANTITY_TO' => NULL,
            'SORT_FROM' => 0,
            'SORT_TO' => INF,
          ),
        ),
        'ITEM_MEASURE_RATIOS' =>
        array (
          865 =>
          array (
            'ID' => 865,
            'RATIO' => 1,
            'IS_DEFAULT' => 'Y',
            'PRODUCT_ID' => '11173',
          ),
        ),
        'ITEM_MEASURE' =>
        array (
          'ID' => 5,
          'TITLE' => 'шт',
          '~TITLE' => 'шт',
        ),
        'ITEM_MEASURE_RATIO_SELECTED' => 865,
        'ITEM_QUANTITY_RANGE_SELECTED' => 'ZERO-INF',
        'ITEM_PRICE_SELECTED' => 0,
        'CHECK_QUANTITY' => false,
        'CAN_BUY' => true,
        'ITEM_PRICES_CAN_BUY' => true,
      ),
    ),
  ),
  7 =>
  array (
    'ID' => 1263,
    'NAME' => 'Клей Pera MSP - 300',
    'CATALOG_PRICE_1' => NULL,
    'CATALOG_CURRENCY_1' => NULL,
    'ITEM_PRICES' =>
    array (
      0 =>
      array (
        'UNROUND_BASE_PRICE' => 8604.959,
        'UNROUND_PRICE' => 8604.959,
        'BASE_PRICE' => 8604.959,
        'PRICE' => 8604.959,
        'ID' => '833',
        'PRICE_TYPE_ID' => '1',
        'CURRENCY' => 'RUB',
        'DISCOUNT' => 0,
        'PERCENT' => 0,
        'QUANTITY_FROM' => NULL,
        'QUANTITY_TO' => NULL,
        'QUANTITY_HASH' => 'ZERO-INF',
        'MEASURE_RATIO_ID' => NULL,
        'PRINT_BASE_PRICE' => '8 605 р',
        'RATIO_BASE_PRICE' => 8604.959,
        'PRINT_RATIO_BASE_PRICE' => '8 605 р',
        'PRINT_PRICE' => '8 605 р',
        'RATIO_PRICE' => 8604.959,
        'PRINT_RATIO_PRICE' => '8 605 р',
        'PRINT_DISCOUNT' => '0 р',
        'RATIO_DISCOUNT' => 0,
        'PRINT_RATIO_DISCOUNT' => '0 р',
        'MIN_QUANTITY' => 1,
      ),
    ),
    'OFFERS' =>
    array (
    ),
  ),
  8 =>
  array (
    'ID' => 2235,
    'NAME' => 'Senco SHF15 - гвоздезабивной инструмент ',
    'CATALOG_PRICE_1' => NULL,
    'CATALOG_CURRENCY_1' => NULL,
    'ITEM_PRICES' =>
    array (
      0 =>
      array (
        'UNROUND_BASE_PRICE' => 49540.0,
        'UNROUND_PRICE' => 49540.0,
        'BASE_PRICE' => 49540.0,
        'PRICE' => 49540.0,
        'ID' => '2337',
        'PRICE_TYPE_ID' => '1',
        'CURRENCY' => 'RUB',
        'DISCOUNT' => 0,
        'PERCENT' => 0,
        'QUANTITY_FROM' => NULL,
        'QUANTITY_TO' => NULL,
        'QUANTITY_HASH' => 'ZERO-INF',
        'MEASURE_RATIO_ID' => NULL,
        'PRINT_BASE_PRICE' => '49 540 р',
        'RATIO_BASE_PRICE' => 49540.0,
        'PRINT_RATIO_BASE_PRICE' => '49 540 р',
        'PRINT_PRICE' => '49 540 р',
        'RATIO_PRICE' => 49540.0,
        'PRINT_RATIO_PRICE' => '49 540 р',
        'PRINT_DISCOUNT' => '0 р',
        'RATIO_DISCOUNT' => 0,
        'PRINT_RATIO_DISCOUNT' => '0 р',
        'MIN_QUANTITY' => 1,
      ),
    ),
    'OFFERS' =>
    array (
    ),
  ),
  9 =>
  array (
    'ID' => 2390,
    'NAME' => 'Senco FinishPro 15 - шпилькозабивной инструмент',
    'CATALOG_PRICE_1' => NULL,
    'CATALOG_CURRENCY_1' => NULL,
    'ITEM_PRICES' =>
    array (
    ),
    'OFFERS' =>
    array (
      0 =>
      array (
        'ID' => 4825,
        '~ID' => '4825',
        'IBLOCK_ID' => 17,
        '~IBLOCK_ID' => '17',
        'PROPERTY_343_VALUE' => '2390',
        '~PROPERTY_343_VALUE' => '2390',
        'PROPERTY_343_VALUE_ID' => '4825:343',
        '~PROPERTY_343_VALUE_ID' => '4825:343',
        'SORT' => '500',
        '~SORT' => '500',
        'PREVIEW_PICTURE' => NULL,
        '~PREVIEW_PICTURE' => NULL,
        'DETAIL_PICTURE' =>
        array (
          'ID' => '5074',
          'TIMESTAMP_X' => '25.07.2014 03:21:22',
          'MODULE_ID' => 'iblock',
          'HEIGHT' => '225',
          'WIDTH' => '300',
          'FILE_SIZE' => '7217',
          'CONTENT_TYPE' => 'image/jpeg',
          'SUBDIR' => 'iblock/dcf',
          'FILE_NAME' => 'dcf8772a9a9cf411a2d244a7ac052606.jpg',
          'ORIGINAL_NAME' => 'FinishPro151.jpg',
          'DESCRIPTION' => '',
          'HANDLER_ID' => NULL,
          'EXTERNAL_ID' => NULL,
          'SRC' => '/upload/iblock/dcf/dcf8772a9a9cf411a2d244a7ac052606.jpg',
          'UNSAFE_SRC' => '/upload/iblock/dcf/dcf8772a9a9cf411a2d244a7ac052606.jpg',
          'SAFE_SRC' => '/upload/iblock/dcf/dcf8772a9a9cf411a2d244a7ac052606.jpg',
          'ALT' => '',
          'TITLE' => '',
        ),
        '~DETAIL_PICTURE' => '5074',
        'CATALOG_QUANTITY' => '1',
        '~CATALOG_QUANTITY' => '1',
        'CATALOG_QUANTITY_RESERVED' => '0',
        '~CATALOG_QUANTITY_RESERVED' => '0',
        'CATALOG_QUANTITY_TRACE' => 'N',
        '~CATALOG_QUANTITY_TRACE' => 'N',
        'CATALOG_QUANTITY_TRACE_ORIG' => 'D',
        '~CATALOG_QUANTITY_TRACE_ORIG' => 'D',
        'CATALOG_CAN_BUY_ZERO' => 'Y',
        '~CATALOG_CAN_BUY_ZERO' => 'Y',
        'CATALOG_CAN_BUY_ZERO_ORIG' => 'D',
        '~CATALOG_CAN_BUY_ZERO_ORIG' => 'D',
        'CATALOG_NEGATIVE_AMOUNT_TRACE' => 'Y',
        '~CATALOG_NEGATIVE_AMOUNT_TRACE' => 'Y',
        'CATALOG_NEGATIVE_AMOUNT_ORIG' => 'D',
        '~CATALOG_NEGATIVE_AMOUNT_ORIG' => 'D',
        'CATALOG_SUBSCRIBE' => 'Y',
        '~CATALOG_SUBSCRIBE' => 'Y',
        'CATALOG_SUBSCRIBE_ORIG' => 'D',
        '~CATALOG_SUBSCRIBE_ORIG' => 'D',
        'CATALOG_AVAILABLE' => 'Y',
        '~CATALOG_AVAILABLE' => 'Y',
        'CATALOG_WEIGHT' => '0',
        '~CATALOG_WEIGHT' => '0',
        'CATALOG_WIDTH' => '0',
        '~CATALOG_WIDTH' => '0',
        'CATALOG_LENGTH' => '0',
        '~CATALOG_LENGTH' => '0',
        'CATALOG_HEIGHT' => '0',
        '~CATALOG_HEIGHT' => '0',
        'CATALOG_MEASURE' => 5,
        '~CATALOG_MEASURE' => '5',
        'CATALOG_VAT' => NULL,
        '~CATALOG_VAT' => NULL,
        'CATALOG_VAT_ID' => '0',
        '~CATALOG_VAT_ID' => '0',
        'CATALOG_VAT_INCLUDED' => 'N',
        '~CATALOG_VAT_INCLUDED' => 'N',
        'CATALOG_PRICE_TYPE' => 'S',
        '~CATALOG_PRICE_TYPE' => 'S',
        'CATALOG_RECUR_SCHEME_TYPE' => 'D',
        '~CATALOG_RECUR_SCHEME_TYPE' => 'D',
        'CATALOG_RECUR_SCHEME_LENGTH' => '0',
        '~CATALOG_RECUR_SCHEME_LENGTH' => '0',
        'CATALOG_TRIAL_PRICE_ID' => NULL,
        '~CATALOG_TRIAL_PRICE_ID' => NULL,
        'CATALOG_WITHOUT_ORDER' => 'N',
        '~CATALOG_WITHOUT_ORDER' => 'N',
        'CATALOG_SELECT_BEST_PRICE' => 'Y',
        '~CATALOG_SELECT_BEST_PRICE' => 'Y',
        'CATALOG_PURCHASING_PRICE' => '0.00',
        '~CATALOG_PURCHASING_PRICE' => '0.00',
        'CATALOG_PURCHASING_CURRENCY' => 'RUB',
        '~CATALOG_PURCHASING_CURRENCY' => 'RUB',
        'CATALOG_TYPE' => 4,
        '~CATALOG_TYPE' => '4',
        'CATALOG_BUNDLE' => 'N',
        '~CATALOG_BUNDLE' => 'N',
        'SORT_HASH' => '55a05e0c64b1da4d5b3b5ae83ebd371e',
        'LINK_ELEMENT_ID' => 2390,
        'PROPERTIES' =>
        array (
        ),
        'DISPLAY_PROPERTIES' =>
        array (
        ),
        'PRODUCT' =>
        array (
          'TYPE' => 4,
          'AVAILABLE' => 'Y',
          'MEASURE' => 5,
          'VAT_ID' => NULL,
          'VAT_RATE' => NULL,
          'VAT_INCLUDED' => 'N',
          'QUANTITY' => '1',
          'QUANTITY_TRACE' => 'N',
          'CAN_BUY_ZERO' => 'Y',
          'SUBSCRIPTION' => NULL,
          'BUNDLE' => 'N',
        ),
        'ITEM_PRICE_MODE' => 'S',
        'ITEM_PRICES' =>
        array (
          0 =>
          array (
            'UNROUND_BASE_PRICE' => 21200.0,
            'UNROUND_PRICE' => 21200.0,
            'BASE_PRICE' => 21200.0,
            'PRICE' => 21200.0,
            'ID' => '4060',
            'PRICE_TYPE_ID' => '1',
            'CURRENCY' => 'RUB',
            'DISCOUNT' => 0,
            'PERCENT' => 0,
            'QUANTITY_FROM' => NULL,
            'QUANTITY_TO' => NULL,
            'QUANTITY_HASH' => 'ZERO-INF',
            'MEASURE_RATIO_ID' => NULL,
            'PRINT_BASE_PRICE' => '21 200 р',
            'RATIO_BASE_PRICE' => 21200.0,
            'PRINT_RATIO_BASE_PRICE' => '21 200 р',
            'PRINT_PRICE' => '21 200 р',
            'RATIO_PRICE' => 21200.0,
            'PRINT_RATIO_PRICE' => '21 200 р',
            'PRINT_DISCOUNT' => '0 р',
            'RATIO_DISCOUNT' => 0,
            'PRINT_RATIO_DISCOUNT' => '0 р',
            'MIN_QUANTITY' => 1,
          ),
        ),
        'ITEM_QUANTITY_RANGES' =>
        array (
          'ZERO-INF' =>
          array (
            'HASH' => 'ZERO-INF',
            'QUANTITY_FROM' => NULL,
            'QUANTITY_TO' => NULL,
            'SORT_FROM' => 0,
            'SORT_TO' => INF,
          ),
        ),
        'ITEM_MEASURE_RATIOS' =>
        array (
          602 =>
          array (
            'ID' => 602,
            'RATIO' => 1,
            'IS_DEFAULT' => 'Y',
            'PRODUCT_ID' => '4825',
          ),
        ),
        'ITEM_MEASURE' =>
        array (
          'ID' => 5,
          'TITLE' => 'шт',
          '~TITLE' => 'шт',
        ),
        'ITEM_MEASURE_RATIO_SELECTED' => 602,
        'ITEM_QUANTITY_RANGE_SELECTED' => 'ZERO-INF',
        'ITEM_PRICE_SELECTED' => 0,
        'CHECK_QUANTITY' => false,
        'CAN_BUY' => true,
        'ITEM_PRICES_CAN_BUY' => true,
      ),
      1 =>
      array (
        'ID' => 4826,
        '~ID' => '4826',
        'IBLOCK_ID' => 17,
        '~IBLOCK_ID' => '17',
        'PROPERTY_343_VALUE' => '2390',
        '~PROPERTY_343_VALUE' => '2390',
        'PROPERTY_343_VALUE_ID' => '4826:343',
        '~PROPERTY_343_VALUE_ID' => '4826:343',
        'SORT' => '501',
        '~SORT' => '501',
        'PREVIEW_PICTURE' => NULL,
        '~PREVIEW_PICTURE' => NULL,
        'DETAIL_PICTURE' =>
        array (
          'ID' => '5075',
          'TIMESTAMP_X' => '25.07.2014 03:26:52',
          'MODULE_ID' => 'iblock',
          'HEIGHT' => '300',
          'WIDTH' => '300',
          'FILE_SIZE' => '19418',
          'CONTENT_TYPE' => 'image/jpeg',
          'SUBDIR' => 'iblock/7fc',
          'FILE_NAME' => '7fc1383ba0536c2d75051aa0932f30a7.jpg',
          'ORIGINAL_NAME' => 'AX13EAAP Шпилька для пневмоинструмента.jpg',
          'DESCRIPTION' => '',
          'HANDLER_ID' => NULL,
          'EXTERNAL_ID' => NULL,
          'SRC' => '/upload/iblock/7fc/7fc1383ba0536c2d75051aa0932f30a7.jpg',
          'UNSAFE_SRC' => '/upload/iblock/7fc/7fc1383ba0536c2d75051aa0932f30a7.jpg',
          'SAFE_SRC' => '/upload/iblock/7fc/7fc1383ba0536c2d75051aa0932f30a7.jpg',
          'ALT' => '',
          'TITLE' => '',
        ),
        '~DETAIL_PICTURE' => '5075',
        'CATALOG_QUANTITY' => '1',
        '~CATALOG_QUANTITY' => '1',
        'CATALOG_QUANTITY_RESERVED' => '0',
        '~CATALOG_QUANTITY_RESERVED' => '0',
        'CATALOG_QUANTITY_TRACE' => 'N',
        '~CATALOG_QUANTITY_TRACE' => 'N',
        'CATALOG_QUANTITY_TRACE_ORIG' => 'D',
        '~CATALOG_QUANTITY_TRACE_ORIG' => 'D',
        'CATALOG_CAN_BUY_ZERO' => 'Y',
        '~CATALOG_CAN_BUY_ZERO' => 'Y',
        'CATALOG_CAN_BUY_ZERO_ORIG' => 'D',
        '~CATALOG_CAN_BUY_ZERO_ORIG' => 'D',
        'CATALOG_NEGATIVE_AMOUNT_TRACE' => 'Y',
        '~CATALOG_NEGATIVE_AMOUNT_TRACE' => 'Y',
        'CATALOG_NEGATIVE_AMOUNT_ORIG' => 'D',
        '~CATALOG_NEGATIVE_AMOUNT_ORIG' => 'D',
        'CATALOG_SUBSCRIBE' => 'Y',
        '~CATALOG_SUBSCRIBE' => 'Y',
        'CATALOG_SUBSCRIBE_ORIG' => 'D',
        '~CATALOG_SUBSCRIBE_ORIG' => 'D',
        'CATALOG_AVAILABLE' => 'Y',
        '~CATALOG_AVAILABLE' => 'Y',
        'CATALOG_WEIGHT' => '0',
        '~CATALOG_WEIGHT' => '0',
        'CATALOG_WIDTH' => '0',
        '~CATALOG_WIDTH' => '0',
        'CATALOG_LENGTH' => '0',
        '~CATALOG_LENGTH' => '0',
        'CATALOG_HEIGHT' => '0',
        '~CATALOG_HEIGHT' => '0',
        'CATALOG_MEASURE' => 5,
        '~CATALOG_MEASURE' => '5',
        'CATALOG_VAT' => NULL,
        '~CATALOG_VAT' => NULL,
        'CATALOG_VAT_ID' => '0',
        '~CATALOG_VAT_ID' => '0',
        'CATALOG_VAT_INCLUDED' => 'N',
        '~CATALOG_VAT_INCLUDED' => 'N',
        'CATALOG_PRICE_TYPE' => 'S',
        '~CATALOG_PRICE_TYPE' => 'S',
        'CATALOG_RECUR_SCHEME_TYPE' => 'D',
        '~CATALOG_RECUR_SCHEME_TYPE' => 'D',
        'CATALOG_RECUR_SCHEME_LENGTH' => '0',
        '~CATALOG_RECUR_SCHEME_LENGTH' => '0',
        'CATALOG_TRIAL_PRICE_ID' => NULL,
        '~CATALOG_TRIAL_PRICE_ID' => NULL,
        'CATALOG_WITHOUT_ORDER' => 'N',
        '~CATALOG_WITHOUT_ORDER' => 'N',
        'CATALOG_SELECT_BEST_PRICE' => 'Y',
        '~CATALOG_SELECT_BEST_PRICE' => 'Y',
        'CATALOG_PURCHASING_PRICE' => '0.00',
        '~CATALOG_PURCHASING_PRICE' => '0.00',
        'CATALOG_PURCHASING_CURRENCY' => 'RUB',
        '~CATALOG_PURCHASING_CURRENCY' => 'RUB',
        'CATALOG_TYPE' => 4,
        '~CATALOG_TYPE' => '4',
        'CATALOG_BUNDLE' => 'N',
        '~CATALOG_BUNDLE' => 'N',
        'SORT_HASH' => '0cad7f1efd6a51d30f404b51237fab09',
        'LINK_ELEMENT_ID' => 2390,
        'PROPERTIES' =>
        array (
        ),
        'DISPLAY_PROPERTIES' =>
        array (
        ),
        'PRODUCT' =>
        array (
          'TYPE' => 4,
          'AVAILABLE' => 'Y',
          'MEASURE' => 5,
          'VAT_ID' => NULL,
          'VAT_RATE' => NULL,
          'VAT_INCLUDED' => 'N',
          'QUANTITY' => '1',
          'QUANTITY_TRACE' => 'N',
          'CAN_BUY_ZERO' => 'Y',
          'SUBSCRIPTION' => NULL,
          'BUNDLE' => 'N',
        ),
        'ITEM_PRICE_MODE' => 'S',
        'ITEM_PRICES' =>
        array (
          0 =>
          array (
            'UNROUND_BASE_PRICE' => 125.0,
            'UNROUND_PRICE' => 125.0,
            'BASE_PRICE' => 125.0,
            'PRICE' => 125.0,
            'ID' => '4061',
            'PRICE_TYPE_ID' => '1',
            'CURRENCY' => 'RUB',
            'DISCOUNT' => 0,
            'PERCENT' => 0,
            'QUANTITY_FROM' => NULL,
            'QUANTITY_TO' => NULL,
            'QUANTITY_HASH' => 'ZERO-INF',
            'MEASURE_RATIO_ID' => NULL,
            'PRINT_BASE_PRICE' => '125 р',
            'RATIO_BASE_PRICE' => 125.0,
            'PRINT_RATIO_BASE_PRICE' => '125 р',
            'PRINT_PRICE' => '125 р',
            'RATIO_PRICE' => 125.0,
            'PRINT_RATIO_PRICE' => '125 р',
            'PRINT_DISCOUNT' => '0 р',
            'RATIO_DISCOUNT' => 0,
            'PRINT_RATIO_DISCOUNT' => '0 р',
            'MIN_QUANTITY' => 1,
          ),
        ),
        'ITEM_QUANTITY_RANGES' =>
        array (
          'ZERO-INF' =>
          array (
            'HASH' => 'ZERO-INF',
            'QUANTITY_FROM' => NULL,
            'QUANTITY_TO' => NULL,
            'SORT_FROM' => 0,
            'SORT_TO' => INF,
          ),
        ),
        'ITEM_MEASURE_RATIOS' =>
        array (
          601 =>
          array (
            'ID' => 601,
            'RATIO' => 1,
            'IS_DEFAULT' => 'Y',
            'PRODUCT_ID' => '4826',
          ),
        ),
        'ITEM_MEASURE' =>
        array (
          'ID' => 5,
          'TITLE' => 'шт',
          '~TITLE' => 'шт',
        ),
        'ITEM_MEASURE_RATIO_SELECTED' => 601,
        'ITEM_QUANTITY_RANGE_SELECTED' => 'ZERO-INF',
        'ITEM_PRICE_SELECTED' => 0,
        'CHECK_QUANTITY' => false,
        'CAN_BUY' => true,
        'ITEM_PRICES_CAN_BUY' => true,
      ),
    ),
  ),
  10 =>
  array (
    'ID' => 2392,
    'NAME' => 'Senco PC1010 - компрессор безмаслянный',
    'CATALOG_PRICE_1' => NULL,
    'CATALOG_CURRENCY_1' => NULL,
    'ITEM_PRICES' =>
    array (
      0 =>
      array (
        'UNROUND_BASE_PRICE' => 29100.0,
        'UNROUND_PRICE' => 29100.0,
        'BASE_PRICE' => 29100.0,
        'PRICE' => 29100.0,
        'ID' => '2478',
        'PRICE_TYPE_ID' => '1',
        'CURRENCY' => 'RUB',
        'DISCOUNT' => 0,
        'PERCENT' => 0,
        'QUANTITY_FROM' => NULL,
        'QUANTITY_TO' => NULL,
        'QUANTITY_HASH' => 'ZERO-INF',
        'MEASURE_RATIO_ID' => NULL,
        'PRINT_BASE_PRICE' => '29 100 р',
        'RATIO_BASE_PRICE' => 29100.0,
        'PRINT_RATIO_BASE_PRICE' => '29 100 р',
        'PRINT_PRICE' => '29 100 р',
        'RATIO_PRICE' => 29100.0,
        'PRINT_RATIO_PRICE' => '29 100 р',
        'PRINT_DISCOUNT' => '0 р',
        'RATIO_DISCOUNT' => 0,
        'PRINT_RATIO_DISCOUNT' => '0 р',
        'MIN_QUANTITY' => 1,
      ),
    ),
    'OFFERS' =>
    array (
    ),
  ),
  11 =>
  array (
    'ID' => 2981,
    'NAME' => 'Гигрометр для измерения влажности воздуха',
    'CATALOG_PRICE_1' => NULL,
    'CATALOG_CURRENCY_1' => NULL,
    'ITEM_PRICES' =>
    array (
      0 =>
      array (
        'UNROUND_BASE_PRICE' => 14941.3379,
        'UNROUND_PRICE' => 14941.3379,
        'BASE_PRICE' => 14941.3379,
        'PRICE' => 14941.3379,
        'ID' => '2934',
        'PRICE_TYPE_ID' => '1',
        'CURRENCY' => 'RUB',
        'DISCOUNT' => 0,
        'PERCENT' => 0,
        'QUANTITY_FROM' => NULL,
        'QUANTITY_TO' => NULL,
        'QUANTITY_HASH' => 'ZERO-INF',
        'MEASURE_RATIO_ID' => NULL,
        'PRINT_BASE_PRICE' => '14 941 р',
        'RATIO_BASE_PRICE' => 14941.3379,
        'PRINT_RATIO_BASE_PRICE' => '14 941 р',
        'PRINT_PRICE' => '14 941 р',
        'RATIO_PRICE' => 14941.3379,
        'PRINT_RATIO_PRICE' => '14 941 р',
        'PRINT_DISCOUNT' => '0 р',
        'RATIO_DISCOUNT' => 0,
        'PRINT_RATIO_DISCOUNT' => '0 р',
        'MIN_QUANTITY' => 1,
      ),
    ),
    'OFFERS' =>
    array (
    ),
  ),
  12 =>
  array (
    'ID' => 213,
    'NAME' => 'Гигрометр для анализа влажности бетона.',
    'CATALOG_PRICE_1' => NULL,
    'CATALOG_CURRENCY_1' => NULL,
    'ITEM_PRICES' =>
    array (
      0 =>
      array (
        'UNROUND_BASE_PRICE' => 18000.0,
        'UNROUND_PRICE' => 18000.0,
        'BASE_PRICE' => 18000.0,
        'PRICE' => 18000.0,
        'ID' => '30',
        'PRICE_TYPE_ID' => '1',
        'CURRENCY' => 'RUB',
        'DISCOUNT' => 0,
        'PERCENT' => 0,
        'QUANTITY_FROM' => NULL,
        'QUANTITY_TO' => NULL,
        'QUANTITY_HASH' => 'ZERO-INF',
        'MEASURE_RATIO_ID' => NULL,
        'PRINT_BASE_PRICE' => '18 000 р',
        'RATIO_BASE_PRICE' => 18000.0,
        'PRINT_RATIO_BASE_PRICE' => '18 000 р',
        'PRINT_PRICE' => '18 000 р',
        'RATIO_PRICE' => 18000.0,
        'PRINT_RATIO_PRICE' => '18 000 р',
        'PRINT_DISCOUNT' => '0 р',
        'RATIO_DISCOUNT' => 0,
        'PRINT_RATIO_DISCOUNT' => '0 р',
        'MIN_QUANTITY' => 1,
      ),
    ),
    'OFFERS' =>
    array (
    ),
  ),
  13 =>
  array (
    'ID' => 216,
    'NAME' => 'Мини-лаборатория остаточной влажности бетона',
    'CATALOG_PRICE_1' => NULL,
    'CATALOG_CURRENCY_1' => NULL,
    'ITEM_PRICES' =>
    array (
      0 =>
      array (
        'UNROUND_BASE_PRICE' => 66101.7305,
        'UNROUND_PRICE' => 66101.7305,
        'BASE_PRICE' => 66101.7305,
        'PRICE' => 66101.7305,
        'ID' => '32',
        'PRICE_TYPE_ID' => '1',
        'CURRENCY' => 'RUB',
        'DISCOUNT' => 0,
        'PERCENT' => 0,
        'QUANTITY_FROM' => NULL,
        'QUANTITY_TO' => NULL,
        'QUANTITY_HASH' => 'ZERO-INF',
        'MEASURE_RATIO_ID' => NULL,
        'PRINT_BASE_PRICE' => '66 102 р',
        'RATIO_BASE_PRICE' => 66101.7305,
        'PRINT_RATIO_BASE_PRICE' => '66 102 р',
        'PRINT_PRICE' => '66 102 р',
        'RATIO_PRICE' => 66101.7305,
        'PRINT_RATIO_PRICE' => '66 102 р',
        'PRINT_DISCOUNT' => '0 р',
        'RATIO_DISCOUNT' => 0,
        'PRINT_RATIO_DISCOUNT' => '0 р',
        'MIN_QUANTITY' => 1,
      ),
    ),
    'OFFERS' =>
    array (
    ),
  ),
  14 =>
  array (
    'ID' => 210,
    'NAME' => 'Прибор для анализа поверхностной прочности.',
    'CATALOG_PRICE_1' => NULL,
    'CATALOG_CURRENCY_1' => NULL,
    'ITEM_PRICES' =>
    array (
      0 =>
      array (
        'UNROUND_BASE_PRICE' => 2600.0,
        'UNROUND_PRICE' => 2600.0,
        'BASE_PRICE' => 2600.0,
        'PRICE' => 2600.0,
        'ID' => '28',
        'PRICE_TYPE_ID' => '1',
        'CURRENCY' => 'RUB',
        'DISCOUNT' => 0,
        'PERCENT' => 0,
        'QUANTITY_FROM' => NULL,
        'QUANTITY_TO' => NULL,
        'QUANTITY_HASH' => 'ZERO-INF',
        'MEASURE_RATIO_ID' => NULL,
        'PRINT_BASE_PRICE' => '2 600 р',
        'RATIO_BASE_PRICE' => 2600.0,
        'PRINT_RATIO_BASE_PRICE' => '2 600 р',
        'PRINT_PRICE' => '2 600 р',
        'RATIO_PRICE' => 2600.0,
        'PRINT_RATIO_PRICE' => '2 600 р',
        'PRINT_DISCOUNT' => '0 р',
        'RATIO_DISCOUNT' => 0,
        'PRINT_RATIO_DISCOUNT' => '0 р',
        'MIN_QUANTITY' => 1,
      ),
    ),
    'OFFERS' =>
    array (
    ),
  ),
);
