name: Code Formatting

on:
    push:
        # don't rebuild image if someone only edited unrelated files
        paths-ignore:
            - 'README.md'
    pull_request:
        # don't rebuild image if someone only edited unrelated files
        paths-ignore:
            - 'README.md'

jobs:
    code-formatting:
        name: Code Formatting
        runs-on: ubuntu-20.04
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    submodules: 'true'

            # has built-in cache functionality
            # see https://github.com/actions/setup-node#caching-packages-dependencies
            -   name: Install Node (with cache)
                uses: actions/setup-node@v2
                with:
                    node-version: '16.13.2'
                    cache: 'npm'

            -   name: Display Node And Npm versions
                run: |
                    node -v
                    npm -v

            -   name: Install Npm Dependencies
                run: npm install

            -   name: Npm Format
                run: npm run format

            -   name: Run php-cs-fixer
                uses: docker://oskarstark/php-cs-fixer-ga
                with:
                    args: --config=.php-cs-fixer.php --allow-risky=yes

            -   name: Commit Changes
                uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: PHP CS changes

