name: Deploy 2

on:
    - push

jobs:
    ssh-swarm:
        name: SSH And Swarm
        runs-on: ubuntu-20.04
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v2

            -   name: Assign Content To Env Variable
                run: |
                    echo "DOCKER_STACK_YML<<EOF" >> $GITHUB_ENV
                    $(< docker-stack.template.yml) >> $GITHUB_ENV
                    echo "EOF" >> $GITHUB_ENV

            -   name: executing remote ssh commands ssh key
                uses: appleboy/ssh-action@master
                env:
                    APP_NAME: "Market Parket"
                    APP_KEY: ${{ secrets.APP_KEY }}
                    MYSQL_USER: ${{ secrets.MYSQL_USER }}
                    MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
                    MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
                    DOCKER_STACK_YML: ${{ env.DOCKER_STACK_YML }}
                with:
                    host: ${{ secrets.HOST_IP }}
                    username: ${{ secrets.HOST_USERNAME }}
                    key: ${{ secrets.HOST_KEY }}
                    port: ${{ secrets.HOST_PORT }}
                    envs: APP_NAME,APP_KEY,APP_URL,MYSQL_USER,MYSQL_PASSWORD,MYSQL_ROOT_PASSWORD
                    #script: docker-compose --file docker-stack.template.yml config | docker stack deploy mpl -c -
                    script: echo "$DOCKER_STACK_YML" > docker-stack.template.yml
