name: Deploy

on:
    workflow_run:
        workflows: ["Docker Image Push"]
        types: [completed]
        branches:
            -   'master'
            -   'develop'
            -   'testing-actions'

jobs:
    on-success:
        runs-on: ubuntu-20.04
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v2

            -   name: Assign Content To Env Variable
                run: |
                    echo 'DOCKER_STACK_YML<<EOF' >> $GITHUB_ENV
                    cat docker-stack.template.yml >> $GITHUB_ENV
                    echo 'EOF' >> $GITHUB_ENV

            -   name: executing remote ssh commands ssh key
                uses: appleboy/ssh-action@master
                env:
                    APP_NAME: "Market Parket"
                    APP_KEY: ${{ secrets.APP_KEY }}
                    MYSQL_USER: ${{ secrets.MYSQL_USER }}
                    MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
                    MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
                    DOCKER_STACK_YML: ${{ env.DOCKER_STACK_YML }}
                    IMAGE_APP: ${{ secrets.DOCKER_HUB_USERNAME }}/mpl
                    IMAGE_APP_TAG: ${{ github.sha }}
                with:
                    host: ${{ secrets.HOST_IP }}
                    username: ${{ secrets.HOST_USERNAME }}
                    key: ${{ secrets.HOST_KEY }}
                    port: ${{ secrets.HOST_PORT }}
                    envs: APP_NAME,APP_KEY,APP_URL,MYSQL_USER,MYSQL_PASSWORD,MYSQL_ROOT_PASSWORD,DOCKER_STACK_YML
                    script: |
                        echo "$DOCKER_STACK_YML" > docker-stack.template.yml
                        docker-compose --file docker-stack.template.yml config | docker stack deploy mpl -c -
    on-failure:
        runs-on: ubuntu-20.04
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
            -   run: echo 'The triggering workflow failed'
