name: Run Tests

on:
    - push

jobs:
    phpunit:
        name: Run Tests
        runs-on: ubuntu-20.04
        steps:
            -   uses: actions/checkout@v2
                with:
                    submodules: 'true'

            -   name: Display Folders
                run: |
                    ls -al
                    ls -al docker

            -   name: Display Docker Version
                run: |
                    docker -v
                    docker-compose -v

            -   name: Run Docker Compose
                run: docker-compose up -d --build

            -   name: Run Php Artisan Test
                run: php artisan test
