name: Run tests

on: [ push ]

jobs:
    phpunit:
        name: Run tests
        runs-on: ubuntu-20.04
        steps:
            -   uses: actions/checkout@v2

            -   name: Check Docker Version
                run: |
                    docker -v
                    docker-compose -v
