name: Run Tests

on:
    - push

jobs:
    phpunit:
        name: Run Tests
        runs-on: ubuntu-20.04
        steps:
            -   uses: actions/checkout@v2
                with:
                    submodules: 'true'

            -   name: Display Docker Version
                run: |
                    docker -v
                    docker-compose -v

            -   name: Run Docker Compose
                run: docker-compose -f docker-compose.ci.yml up -d --build


            -   name: Get Composer Cache Directory
                id: composer-cache
                run: |
                    docker-compose exec -T app echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-

            -   name: Install Composer Dependencies
                run: docker-compose exec -T -e COMPOSER_AUTH="${secrets.COMPOSER_AUTH}" app composer install -n --prefer-dist

            -   name: Run Php Artisan Test
                # -T option because of https://github.com/docker/compose/issues/7306#issuecomment-602163499
                run: docker-compose exec -T app php artisan test
