name: Run Tests

on:
    - push

jobs:
    phpunit:
        name: Run Tests
        runs-on: ubuntu-20.04
        steps:
            -   uses: actions/checkout@v2

            -   name: Display Docker Version
                run: |
                    docker -v
                    docker-compose -v
